### PR TITLE
add alc256 layout-id 68 for nuc9 support

### PR DESCRIPTION
**Pull request by littlesum**

### CODE REVIEW

**Comment by Core-i99** [comment]
Seems like you forgot to add layout xml and platforms xml to the info.plist of the codec. 

See: 
https://github.com/acidanthera/AppleALC/blob/master/Resources/ALC256/Info.plist

**Comment by littlesum** [comment]
> Seems like you forgot to add layout xml and platforms xml to the info.plist of the codec.
> 
> See: https://github.com/acidanthera/AppleALC/blob/master/Resources/ALC256/Info.plist

thanks for remind. I fixed this

**Comment by Andrey1970AppleLife** [comment]
Delete plist tags from xml.

**Comment by Andrey1970AppleLife** [comment]
You ignored my post. Сlosed.

**Pull request closed without merging**
