### PR TITLE
Add patch by vasishath to fix internal mic gain adjustment (this fix …

### PR DESCRIPTION
**Pull request by Luca1991**
…microphone volume slider in system preferences)

Hi all,
On my laptop (Lenovo Z70-80 with CX20751) the microphone volume slider in system preferences was broken.
The microphone was always set at maximum volume, even when muted (slide set to the left).
This patch made by vasishath fixed the same issue on a similar conexant card, and turns out it is valid for CX20751 too.
So, this patch just apply his patch on the CX20751 plist! Now microphone volume slider works!! 

ALL CREDITS GOES TO VASISHATH!! I just ported it to CX20751 configuration file.

### CODE REVIEW

**Comment by Ab2774** [comment]
Hi, have a similar issue here, this patch doesn't seem to work on Realtek cards, wonder if there's a similar one for Realtek cards.
Cheers

**Comment by Andrey1970AppleLife** [comment]
Please fix formatting info.plist

**Comment by Luca1991** [comment]
> Please fix formatting info.plist

Oh sh*t, sorry about that! I'll fix it asap!

**Comment by Luca1991** [comment]
@Andrey1970AppleLife Indentation fixed. This should be ok now!

@Ab2774 I don't know honeslty. Try to search in the repo for a similar card that is fully working and try to figure out what patches are missing in your configuration.

**Pull request merged**
