### PR TITLE
layout-id 96 for Realtek ALC257 - Lenovo Thinkpad L390

### PR DESCRIPTION
**Pull request by antoniomcr96**
- Supports internal microphone/speakers - NodeID: 18 (0x12) and 20 (0x14) ;
- Supports external jack for microphone/headphones - NodeID: 25 (0x19) and 33 (0x21);
- Supports ambient noise reduction for microphones;
- Supports auto-switching for speakers/headphones;
- ~~Unluckily, the audio is sometimes distorted (especially with headphones). The problem will be (temporary) fixed if you activate the microphone (for example, open the audio preferences pane).~~ The problem seems to be fixed.

### CODE REVIEW

**Comment by usr-sse2** [comment]
Is the audio on headphones distorted really "sometimes" or after sleep?

**Comment by antoniomcr96** [comment]
> Is the audio on headphones distorted really "sometimes" or after sleep? Seems half-similar to the problem that I've just solved for my layout.

Thanks for your reply. Unfortunately it’s random. It happens rarely with integrated speakers and more often with external headphones. 
It doesn’t happen after wake (sleep -> wake works well and EAPD appears to be configured correctly). It happens randomly after a few minutes with some sound playing. 
Activating one of the microphones always fixes (temporary) the problem. I have not found anything like this so, despite various attempts, I gave up. 
Just out of curiosity, what was your solution?

**Comment by usr-sse2** [comment]
My problem was always after sleep and only with headphones, and it was 'fixed' by activating Line In (which itself doesn't work at  all) using e. g. System Preferences or QuickTime. The solution was to add EAPD for headphones out and jack sense for Line In, according to the [guide](https://gist.github.com/fewtarius/f691d97513c4f7e527cb41f44c069548).

**Comment by antoniomcr96** [comment]
I updated PinConfig as suggested by that guide. Thank you very much.
I've been listening to music with my headphone for 20 minutes and I haven't experienced any episode of distorted audio. Maybe this fixed the problem!!

**Comment by M69W** [comment]
How could I get the kext  and want to test it?
the [Actions](https://github.com/acidanthera/AppleALC/actions) is awaiting approval from a maintainer in https://github.com/acidanthera/AppleALC/pull/764

**Comment by antoniomcr96** [comment]
> M69W
[AppleALC.kext.zip](https://github.com/acidanthera/AppleALC/files/8131119/AppleALC.kext.zip)
Or compile it by yourself from my repo

**Comment by M69W** [comment]
> @M69W
> 
> [AppleALC.kext.zip](https://github.com/acidanthera/AppleALC/files/8131119/AppleALC.kext.zip) Or compile it by yourself from my repo

ok, thanks

**Comment by antoniomcr96** [comment]
Since usr-sse2's suggestion fixed the distorted audio, i updated the description of the first commit

**Pull request merged**
