### PR TITLE
Add mute button

### PR DESCRIPTION
**Pull request by Ab2774**
Hi
I'm sorry I didn't mention some files are required to make it work 
Thanks

### CODE REVIEW

**Comment by vandroiy2013** [comment]
What do you mean?

**Comment by Ab2774** [comment]
"Platforms20.xml.zlib" Is required to make the mute button work, otherwise, there will be no difference
So sorry for not mentioning that [https://github.com/acidanthera/AppleALC/pull/499](url) in the post.

**Comment by roddy20** [comment]
why ZML are binaries, not XML like all the other resources?

**Comment by Ab2774** [comment]
> why these ZLIB are compressed binaries, not XML like all the other resources?

I don't actually know if I compiled it without them nothing will change, already tried to compile it without the ZILB files.

**Comment by roddy20** [comment]
> I don't actually know, if I compiled it without them nothing will change, already tried to compile it without the ZILB files.
XML is readable and it will be compressed to ZLIB during compilation

**Comment by Ab2774** [comment]
Oh, I installed 1.4.6 version instead of 1.4.7 
That's embarrassing
Thanks anyway

**Pull request closed without merging**
