### PR TITLE
Add MacPeet - alc292 for LENOVO THINKPAD T450_T450s_X240 - ManualMode and Add MacPeet- ALC1220 for Z370 AORUS Gaming 7 - Output SP/HP SwitchMode

### PR DESCRIPTION
**Pull request by MacPeet**
MacPeet - alc292 for LENOVO THINKPAD T450_T450s_X240 - ManualMode
MacPeet- ALC1220 for Z370 AORUS Gaming 7 - Output SP/HP SwitchMode

### CODE REVIEW

**Comment by roddy20** [comment]
> MacPeet - alc292 for LENOVO THINKPAD T450_T450s_X240 - ManualMode

Speaker Node does not require AMP usually . Can you show the dump for that codec?

**Comment by MacPeet** [comment]
[codec_dump.txt](https://github.com/acidanthera/AppleALC/files/4270094/codec_dump.txt)

@roddy20 

all devices work internally and externally (combination socket) with this codec very well

**Comment by roddy20** [comment]
Node 0x02 [Audio Output] wcaps 0x41d: Stereo Amp-Out
  Control: name="Speaker Playback Volume", index=0, device=0
    ControlAmp: chs=3, dir=Out, idx=0, ofs=0
  Device: name="ALC3232 Analog", type="Audio", device=0
  Amp-Out caps: ofs=0x57, nsteps=0x57, stepsize=0x02, mute=0
  Amp-Out vals:  [0x4c 0x4c]
  Converter: stream=5, channel=0
it is Out AMP only
why <key>MuteInputAmp</key><true/> etc?

**Comment by Sniki** [comment]
@MacPeet does your external mic (LineIn) work when you plug headsets that have microphone as well ?
Do you have static noise, do you use it without codeccommander and ALCPlugFix ?

**Comment by MacPeet** [comment]
@roddy20 

Ok, one AMP too much.
It has no negative effects here.

@Sniki 

Yes, external microphone (LineIn) and headphone (as LineOut) both work when I connect headsets with a microphone.
Static noise only in SwitchMode (headphone).
Therefore this codec in ManualMode.
I don't use Codec Commander.

**Comment by Sniki** [comment]
@MacPeet i have same codec and i have a Lenovo ThinkPad T440S and X240
I prefer switchmode (automatic) and that's what we are trying to accomplish (fix the static noise).

Do you have a Docking Station ?, i have done the codec_dump with Docking Station and already patched as well but just trying to solve the static noise with auto switch mode.

This codec also works on: L440, L450, T440, T440P, T440S, X250
If you want to add dock support as well here is the dump attached into the conversation:
[Realtek.ALC3232.Dump.txt](https://github.com/acidanthera/AppleALC/files/4270230/Realtek.ALC3232.Dump.txt)

**Comment by MacPeet** [comment]
@Sniki 

I also prefer SwitchMode if it works.
We have been testing for a long time. Unfortunately, in no configuration in SwitchMode without noise.
ManualMode is therefore a good alternative with functionality.

No, I don't have a docking station for my T450s.
The other trial users with T450 and X240 also not, I think.

**Comment by Sniki** [comment]
> @Sniki
> 
> I also prefer SwitchMode if it works.
> We have been testing for a long time. Unfortunately, in no configuration in SwitchMode without noise.
> ManualMode is therefore a good alternative with functionality.
> 
> No, I don't have a docking station for my T450s.
> The other trial users with T450 and X240 also not, I think.

Auto mode works with CodecCommandef.kext + my fork of AlCPlugFix but that seems to complicated, i wanted a cleaner setup with only AppleALC.

Why are u using LineOut instead of Headphones btw ?

**Comment by MacPeet** [comment]
@Sniki 

Setup only with AppleALC is better for other users.
Configuration as headphones always with noise.
Configuration as LineOut no noise and full function of the combination socket.

**Comment by Sniki** [comment]
> @Sniki
> 
> Setup only with AppleALC is better for other users.
> Configuration as headphones always with noise.
> Configuration as LineOut no noise and full function of the combination socket.

Nice, i will do some experimenting now and try leaving it as LineOut in Auto switch mode and see if i can manage to fix that.

**Comment by jestercore** [comment]
What does mean ManualMode vs SwitchMode? There are 15, 28, and 32 layouts for ALC292 to T450s, which one is better?

Also, layout 28 and 32 are very similar, the only difference is:
Layout 28:
			</dict>
			<key>LineIn</key>
			<dict>
				<key>MuteGPIO</key>
				<integer>13422428**54**</integer>
				<key>SignalProcessing</key>
				<dict>

Layout 32:
			</dict>
			<key>LineIn</key>
			<dict>
				<key>MuteGPIO</key>
				<integer>13422428**42**</integer>
				<key>SignalProcessing</key>
				<dict>

**Comment by Core-i99** [comment]
Switch mode is when you plugin the headphone, macos will automatically switch the output to it. 
When manual mode you'll need to change the output by yourself.

**Comment by jestercore** [comment]
> Switch mode is when you plugin the headphone, macos will automatically switch the output to it. When manual mode you'll need to change the output by yourself.

Thank you so much.
Also, could you please explain, what is the difference between layout 28 and 32?

unknown

**Comment by Core-i99** [comment]
@jestercore 

See: https://github.com/5T33Z0/AppleALC-Guides/blob/main/AppleALC_Layout-ID/README.md#calculating-mutegpio

**Comment by MacPeet** [comment]
@jestercore 

With id15 (ManualMode), the combination socket on the T450s works natively, without ALCPlugFix and CodecCommander. Headset (HP+Mic ext.) works without additional software.

With id28 (SwitchMode) it probably only works with ALCPlugFix and CodecCommander, otherwise noise on HP.

**Comment by jestercore** [comment]
@MacPeet 
Thanks for your explanation.

With 28 and 32 a have sound, but with hissing to combojack. ALCPlugFix is fixing it.

For some reason with layout 15 I don't have sound at all.
ALCPlugFix and CodecCommander are deleted.
I will try to go layout 15 way, maybe something is wrong in config.plist or system itself.

**Pull request merged**
