### PR TITLE
A new layout id for huawei honor magic book(alc256-id 57)

### PR DESCRIPTION
**Pull request by ROSstudy**
This is a new layout id for huawei honor magic book ,it works well on my magicbook,Solved the problem of no bass before

### CODE REVIEW

**Comment by vit9696** [comment]
Hi, you overwrote pinconfigs for layout 21. Please fix.

**Comment by vit9696** [comment]
Now the plist structure appears to be broken. Please reformat (done automatically by building AppleALC).

**Comment by ROSstudy** [comment]
I am so sorry for that ,thank fou your work

**Comment by askforcherrycola** [comment]
Hi ROSstudy, is your mute key actually muting the system? Cause I have a Huawei Matebook D 14 (which is the same laptop but Huawei branded) and using 57 layout id mute key is not working with my laptop... I can see the animation of mute, but it's not actually muting the sound.

**Pull request merged**
