### PR TITLE
layout-id 39 for Realtek ALC274 - Mechrevo UmiPro3 (Tongfang GM5MG0Y)

### PR DESCRIPTION
**Pull request by harahi**
- Disabled all useless nodes
- Supports internal microphone/speaker
- Supports external jack for headphones, but need to use [ALCPlugFix_Swift](https://github.com/harahi/UmiPro3-Hackintosh/tree/main/ALCPlugFix_Swift) (Thanks to [black-dragon74](https://github.com/black-dragon74))

### CODE REVIEW

**Comment by harahi** [comment]
> You broke structure **data**, shall be in one line. Build kext in Xcode for fix.

Have fixed.

**Comment by andreszerocross** [comment]
> * Disabled all useless nodes
> * Supports internal microphone/speaker
> * Supports external jack for headphones, but need to use [ALCPlugFix_Swift](https://github.com/harahi/UmiPro3-Hackintosh/tree/main/ALCPlugFix_Swift) (Thanks to [black-dragon74](https://github.com/black-dragon74))

Can you upload plist for alcplugfix??? You said you use "AlcPlugFix.app" then it mean you need to create several command verb in plist for Alcplugfix.app. Please upload it

**Comment by harahi** [comment]
> > * Disabled all useless nodes
> > * Supports internal microphone/speaker
> > * Supports external jack for headphones, but need to use [ALCPlugFix_Swift](https://github.com/harahi/UmiPro3-Hackintosh/tree/main/ALCPlugFix_Swift) (Thanks to [black-dragon74](https://github.com/black-dragon74))
>
> Can you upload plist for alcplugfix??? You said you use "AlcPlugFix.app" then it mean you need to create several command verb in plist for Alcplugfix.app. Please upload it

Yes, I uploaded in my repo. Please click **[ALCPlugFix_Swift](https://github.com/harahi/UmiPro3-Hackintosh/tree/main/ALCPlugFix_Swift)**.

**Comment by andreszerocross** [comment]
> > > * Disabled all useless nodes
> > > * Supports internal microphone/speaker
> > > * Supports external jack for headphones, but need to use [ALCPlugFix_Swift](https://github.com/harahi/UmiPro3-Hackintosh/tree/main/ALCPlugFix_Swift) (Thanks to [black-dragon74](https://github.com/black-dragon74))
> > 
> > 
> > Can you upload plist for alcplugfix??? You said you use "AlcPlugFix.app" then it mean you need to create several command verb in plist for Alcplugfix.app. Please upload it
> 
> Yes, I uploaded in my repo. Please click **[ALCPlugFix_Swift](https://github.com/harahi/UmiPro3-Hackintosh/tree/main/ALCPlugFix_Swift)**.

Thanks very much

**Pull request merged**
