### PR TITLE
Custom ALC287 for Lenovo Yoga Slim 7-14IIL05 by Andres ZeroCross

### PR DESCRIPTION
**Pull request by andreszerocross**

### CODE REVIEW

**Comment by Andrey1970AppleLife** [comment]
Please fix pinconfig data in one line.
`<data>AAAAA</data>`

**Comment by andreszerocross** [comment]
> Please fix pinconfig data in one line.
> `<data>AAAAA</data>`

Done

**Comment by Andrey1970AppleLife** [comment]
And AFGLowPowerState, WakeConfigData.

**Comment by andreszerocross** [comment]
> And AFGLowPowerState, WakeConfigData.

Thanks you, i have fixed it

**Comment by Andrey1970AppleLife** [comment]
And AFGLowPowerState

**Comment by andreszerocross** [comment]
> And AFGLowPowerState

I hope it's really done. Sorry for mistake

**Pull request merged**
