### PR TITLE
Layout 11 for ALC S1220A of Asus mb Z270G (IntMic, LineIn and etc. fixes)

### PR DESCRIPTION
**Pull request by kushamot**
No existing layout suits Asus mb Z270G - green output works, but microphone (rear pink) has too low volume after cold boot or sleep (though normal after warm reboot), front mic doesn't work at all. Layout 11 fixes the issue with the mic.

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Hi. 
Where is PinConfig data for this codec?

**Comment by kushamot** [comment]
Hi!
Sorry, missed PinConfig data. Now added. And Platforms11.xml changed also to enable IntSpeaker/Headphones autodetect.

**Comment by vit9696** [comment]
@kushamot might you be able to merge this in one branch (into a single pull request)?

**Comment by kushamot** [comment]
@vit9696 Done. All commits are in this pull request.

**Comment by L4ivi** [comment]
@kushamot Would this layout also be suitable for Asus mb Z270I?

**Comment by kushamot** [comment]
@L4ivi Most probably yes, this layout will suit z270i as both z270g and z270i mb’s have exactly the same Asus version of s1220 codec (s1220a). However I don’t have z270i mb to test. For z270g the layout works perfectly (one month test).

**Pull request merged**
