### PR TITLE
Add ALC285 layout 61 for Lenovo Yoga C740

### PR DESCRIPTION
**Pull request by fewtarius**
* Adds layout 61 for Lenovo Yoga C740

### CODE REVIEW

**Comment by frozenzero123** [comment]
My device is yoga s740! The same is the sound card of alc285. After using your id61, it is found that there are applehda loaded but no sound! When you press the volume key, there is also a window showing the volume bar increase or decrease! But no matter whether it is headphones or speakers, there is no sound, only display!
[S740.zip](https://github.com/acidanthera/AppleALC/files/4808846/S740.zip)

**Comment by fewtarius** [comment]
> My device is yoga s740! The same is the sound card of alc285. After using your id61, it is found that there are applehda loaded but no sound! When you press the volume key, there is also a window showing the volume bar increase or decrease! But no matter whether it is headphones or speakers, there is no sound, only display!Below is the diff of my device！
> [S740.zip](https://github.com/acidanthera/AppleALC/files/4808846/S740.zip)

The S740 and C740 are two very different devices, you shouldn't expect the layouts to be compatible.

**Comment by fewtarius** [comment]
Took a closer look at that model, looks like it is a comet lake device like mine.  No guarantee it'll work with this layout but you will need FakePCIID.kext and FakePCIID_Intel_HDMI_Audio.kext as the comet lake lp controller isn't quite working for us yet.  You also need to specify a Cannon Point LP device id.

Screen Shot 2020-06-21 at 7 18 48 AM

**Comment by frozenzero123** [comment]
> Took a closer look at that model, looks like it is a comet lake device like mine (unless it's Ice Lake?). No guarantee it'll work with this layout but you will need FakePCIID.kext and FakePCIID_Intel_HDMI_Audio.kext. You also need to specify a Cannon Point LP device id, as the Comet Lake LP controller isn't quite working for us yet.
> 
> Screen Shot 2020-06-21 at 7 18 48 AM

Yes ，it is Ice Lake！But I use clover to guide! After I added FakePCIID.kext and FakePCIID_Intel_HDMI_Audio.kext it（AppleHDA） became unable to load! I saw that alcidid=61 is basically the same as my node. It should be said that the configuration used by c740 and s740 is exactly the same! Including sst mic! But I don't know why it cannot be driven!

**Comment by fewtarius** [comment]
> > Took a closer look at that model, looks like it is a comet lake device like mine (unless it's Ice Lake?). No guarantee it'll work with this layout but you will need FakePCIID.kext and FakePCIID_Intel_HDMI_Audio.kext. You also need to specify a Cannon Point LP device id, as the Comet Lake LP controller isn't quite working for us yet.
> > Screen Shot 2020-06-21 at 7 18 48 AM
> 
> Yes ，it is Ice Lake！But I use clover to guide! After I added FakePCIID.kext and FakePCIID_Intel_HDMI_Audio.kext it（AppleHDA） became unable to load! I saw that alcidid=61 is basically the same as my node. It should be said that the configuration used by c740 and s740 is exactly the same! Including sst mic! But I don't know why it cannot be driven!

Could be a number of reasons, conflicting IRQs, some other conflicting patches, something that Clover is doing behind the scenes, etc.  The pull request isn't really the best place to work those issues through though.

**Comment by qpc001** [comment]
Can layout-61 drive the mic when using facetime?

**Comment by fewtarius** [comment]
> Can layout-61 drive the mic when using facetime?

The internal mic is connected via SST rather than through the codec directly and is not compatible with macOS.  It's not enabled at all by this layout.  The jack mic works fine, as do bluetooth audio devices.

**Comment by qpc001** [comment]
> > 使用facetime时，layout-61可以驱动麦克风吗？
> 
> Yoga C740的内部麦克风通过SST而不是通过编解码器直接连接，并且与macOS不兼容。此布局完全未启用它。插孔麦克风和蓝牙音频设备一样工作正常。

yeah, I try the  jack mic it works well, but when I use the airpods2, it just can play the sound but can not the misc.

**Comment by frozenzero123** [comment]
> > > 使用facetime时，layout-61可以驱动麦克风吗？
> > 
> > 
> > Yoga C740的内部麦克风通过SST而不是通过编解码器直接连接，并且与macOS不兼容。此布局完全未启用它。插孔麦克风和蓝牙音频设备一样工作正常。
> 
> yeah, I try the jack mic , it works well.

请问你能共享下你的efi吗？不是全部，只是关于触控板和声卡的部分，热补丁和驱动。如果有c740提取的dsdt就好了，我的设备是s740 正处在驱动不完善的境况！

**Comment by qpc001** [comment]
> > > > 使用facetime时，layout-61可以驱动麦克风吗？
> > > 
> > > 
> > > Yoga C740的内部麦克风通过SST而不是通过编解码器直接连接，并且与macOS不兼容。此布局完全未启用它。插孔麦克风和蓝牙音频设备一样工作正常。
> > 
> > 
> > yeah, I try the jack mic , it works well.
> 
> 请问你能共享下你的efi吗？不是全部，只是关于触控板和声卡的部分，热补丁和驱动。如果有c740提取的dsdt就好了，我的设备是s740 正处在驱动不完善的境况！

这个我不太了解欸，别人帮我调好的，你留个邮箱，我回头发你efi吧

**Comment by frozenzero123** [comment]
> > > > > 使用facetime时，layout-61可以驱动麦克风吗？
> > > > 
> > > > 
> > > > Yoga C740的内部麦克风通过SST而不是通过编解码器直接连接，并且与macOS不兼容。此布局完全未启用它。插孔麦克风和蓝牙音频设备一样工作正常。
> > > 
> > > 
> > > yeah, I try the jack mic , it works well.
> > 
> > 
> > 请问你能共享下你的efi吗？不是全部，只是关于触控板和声卡的部分，热补丁和驱动。如果有c740提取的dsdt就好了，我的设备是s740 正处在驱动不完善的境况！
> 
> 这个我不太了解欸，别人帮我调好的，你留个邮箱，我回头发你efi吧

不清楚是否可以直接联系！如果可以的话 ，麻烦你发到这个邮箱longope230@gmail.com 谢谢🙏

**Comment by ai930** [comment]
惠普 Pavilion Gaming Laptop 15-dk0xxx 笔记本电脑
Codec: Realtek ALC285   Address: 0   DevID: 283902597 (0x10ec0285)

请教大各位帮看看，我仿冒声卡编译AppleALC等都试过了。都不行！

image

**Comment by frozenzero123** [comment]
> 惠普 Pavilion Gaming Laptop 15-dk0xxx 笔记本电脑
> Codec: Realtek ALC285 Address: 0 DevID: 283902597 (0x10ec0285)
> 
> 请教大各位帮看看，我仿冒声卡编译AppleALC等都试过了。都不行！
> 
> image

仿冒时需要在设备pci那里输入device id 仿冒9DC8 而layou id要设置成你需要的 可以是16进制也可以10进制！

**Comment by ai930** [comment]
ok 了。我试了，注入id 21 或者31都可以。不过有破音！声音有时候出现卡顿。。。。。这个有什么好办法解决吗？主要是哪方面的问题啊？

**Pull request merged**
