### PR TITLE
Added ALC269 layout-id 77 for Thunderobot-G7000S

### PR DESCRIPTION
**Pull request by Phoenix-Liang**
Sorry about the previous commit that forgot to add PinConfig to kext.

Note:
> The laptop's separate 3.5mm mic port doesn't work, but the rest is normal.

### CODE REVIEW

**Comment by Andrey1970AppleLife** [comment]
Fix formatting plist, use Xcode.

**Comment by Phoenix-Liang** [comment]
> Fix formatting plist, use Xcode.

Ok, I have formatted plist with Xcode, thank you for your guidance and work.

**Comment by Andrey1970AppleLife** [comment]
Build a kext in Xcode to fix formatting PinConfig.

**Comment by Phoenix-Liang** [comment]
> Build a kext in Xcode to fix formatting PinConfig.

Sorry, my English is not good.
 I'm using Xcode11, which breaks the integrity of `< data >`. Maybe I should try ProperTree next time.Thanks again for your guidance.

**Comment by Andrey1970AppleLife** [comment]
Press Build in xcode.

**Comment by Phoenix-Liang** [comment]
> Press Build in xcode.

I've finished formatting with Xcode's Build capability. Thank you again for your patient guidance.☺

**Pull request merged**
