### PR TITLE
Some updates, additions

### PR DESCRIPTION
**Pull request by wern-apfel**

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Hi. You broke XML structure.

**Comment by wern-apfel** [comment]
Oh, where exactly? The kext works on all 3 computers.

**Comment by vit9696** [comment]
Sorry, not validity-wise but formatting wise. You have xml tags, and we strip them for file size, the newlines we use look also different. I believe doing Clean in Xcode and building again will fix this, and you can push an update.

**Comment by wern-apfel** [comment]
You're right, PlistEditPro formatting is different. Is it ok now? or should I also remove the PeriperialDSP entries?

**Pull request merged**
