### PR TITLE
Fix jack alc298 layout22

### PR DESCRIPTION
**Pull request by yattoz**
I completed the jack sense pin layout for Layout 22 of ALC298, and as I was suggested to make a PR for it, here it is. 
I followed the guide presented here : https://gist.github.com/fewtarius/0ee689cf725c27c43af0aea83b04b882
And I have been using this pin layout for several weeks now, I didn't see any issue with my headphone jack and sleep in all configurations (putting it, removing it while sleeping, re-inserting it while sleeping, etc), so I think it's okay.

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Hi. Did @andreszerocross approved this changes?

**Comment by yattoz** [comment]
No, I didn't contact him at all. I was simply told that, once I'm done finding the pin settings for my layout, I could do a pull request to help everyone, but this wasn't reviewed by anyone.
This pin settings works correctly with my Thinkpad T470 20JN (Syklake generation) with ALC298 Layout 22 for as far as I have tested, but I am the only one who tested it.

**Comment by fewtarius** [comment]
> No, I didn't contact him at all. I was simply told by @fewtarius on the Hackintosh Discord that, once I'm done finding the pin settings for my layout, I could do a pull request to help everyone, but this wasn't reviewed by anyone.
> This pin settings works correctly with my Thinkpad T470 20JN (Syklake generation) with ALC298 Layout 22 on Big Sur for as far as I have tested, but I am the only one who tested it.

If you're updating an existing layout, you definitely want to have it peer reviewed by the layout owner.  Sorry if I didn't make that clear.

**Comment by yattoz** [comment]
Then if @andreszerocross has some time to check this out and verify it works well on his hardware too, it would be nice. I don't know if it's sufficient to ping him here, of if I should leave him a DM on Gitter (I don't know what's considered "good manners" so by default I'd prefer not to importunate someone with direct messages usually).

**Comment by andreszerocross** [comment]
Actually i didn't see any EAPD variable in node id 0x17 in Razer Blade 14 2017 CodecDump in Linux. It looks Thinkpad T470 20JN has EAPD in node 0x17?? And honestly i can't make test this EAPD change to Razer Blade 14 2017.

**Comment by jackjack1-su** [comment]
The same sound card doesn't mean same nodes.
You may need to make new layouts for new devices(That's why there are so many layouts under each card!)
So I suggest @yattoz to make a new layout with the resources you have.

**Comment by vandroiy2013** [comment]
@yattoz 
Hi. You need to make new layout-id for your device. I'm closing this PR.

**Pull request closed without merging**
