### PR TITLE
Update 400 series PCH-LP controller and add layout 61 for ALC285

### PR DESCRIPTION
**Pull request by fewtarius**
* Corrects the pin configuration needed for the ALC285 on the Lenovo Yoga C740 to eliminate "scratchy" audio, fix jacksense, and audio on wake from sleep.
* Updates the 400 series PCH-LP controller to match the Whiskey Lake controller patch definition.  This is not a complete solution as a fake pci id of C89D0000 is still needed for functional audio on this comet lake device.

### CODE REVIEW

**Comment by fewtarius** [comment]
Found a problem with the layout, will submit a new PR when it's fixed.

**Comment by benbender** [comment]
> * Corrects the pin configuration needed for the ALC285 on the Lenovo Yoga C740 to eliminate "scratchy" audio, fix jacksense, and audio on wake from sleep.

@fewtarius Same problems are frequently seen on ALC285 on the X1C6 and ALC257 on the T480 and maybe more. Do you think it would be possible and would you be able and would you be willing to port those patches over (Or give some hints how to do it)?

**Comment by fewtarius** [comment]
@benbender - Find me on the Hackintosh Paradise discord and I'll teach you how to correct it.

**Comment by benbender** [comment]
@fewtarius Can't find you under your nickname. Could you ping me @benben?

**Pull request closed without merging**
