### PR TITLE
Added layoutid 59 ALC292 for Dell M4800 with dockstation support

### PR DESCRIPTION
**Pull request by hansyao**
* Added layoutid 59 in ALC292 for Dell Precision M4800 with dock station support
* Added NVIDIA HDMI for GK107 in 10.13.4+ (tested in nvidia k1100m)
please see the [latest artifacts](https://github.com/hansyao/AppleALC/suites/5725529026/artifacts/189357348) was tested which work perfectly including mic, headset both in built-in and dock station.

### CODE REVIEW

**Review by hansyao — COMMENTED** [review]
* Added layoutid 59 in ALC292 for Dell Precision M4800 with dock station support
* Added NVIDIA HDMI for GK107 in 10.13.4+ (tested in nvidia k1100m)

tested successfully to be merged now.

**Comment by Sniki** [comment]
@hansyao did you actually manage to patch this codec without the static noise / need for AlcPlugFix  ?
Do both jack microphones work ? and how about the switch mode : Automatic or Manual ?

**Comment by hansyao** [comment]
> 

1. Yes. static noise fixed natively. no alcplugfix need.
2. sound outputs fully work in switch mode: automatic
   - left headphone jack (works)
   - dock headphone jack (works)
   - built-in speaker (works)
3. microphones (switch mode: automatic)
    - built-in mic. (works)
    - dock microphone jack (works)
    - left microphone jack. (not work)

The only bug is left microphone jack does not work currently.

**Comment by Sniki** [comment]
> > 
> 
> 1. Yes. static noise fixed natively. no alcplugfix need.
> 2. sound outputs fully work in switch mode: automatic
>    
>    * left headphone jack (works)
>    * dock headphone jack (works)
>    * built-in speaker (works)
> 3. microphones (switch mode: automatic)
>    
>    * built-in mic. (works)
>    * dock microphone jack (works)
>    * left microphone jack. (not work)
> 
> The only bug is left microphone jack does not work currently.

Is it possible to leave laptop jack microphone working instead of the Dock one ?
Just because not everyone may have a dock and people will tend to use more the laptop jack than the dock one with headsets that have microphone.

**Comment by hansyao** [comment]
> > > 
> > 
> > 
> > 
> > 1. Yes. static noise fixed natively. no alcplugfix need.
> > 2. sound outputs fully work in switch mode: automatic
> >    
> >    * left headphone jack (works)
> >    * dock headphone jack (works)
> >    * built-in speaker (works)
> > 3. microphones (switch mode: automatic)
> >    
> >    * built-in mic. (works)
> >    * dock microphone jack (works)
> >    * left microphone jack. (not work)
> > 
> > The only bug is left microphone jack does not work currently.
> 
> Is it possible to leave laptop jack microphone working instead of the Dock one ? Just because not everyone may have a dock and people will tend to use more the laptop jack than the dock one with headsets that have microphone.

Not find the solution, yet. Probably I will look into this and try to make it next built.

**Comment by Core-i99** [comment]
I also have this issue, cant get multiple mics to work. My layout id is 23 foe asrock b365 pro4.

Ports which I have:
- front combo jack (mic + headphone)
- back line out
- back line in
- back mic in (doesn't work)

I've found out this is because of mutegpio, I set the mutegpio to a correct value for the front mic and then back mic doesn't work anymore. But haven't yet looked any further to fix it.

**Comment by hansyao** [comment]
> 
adf


> I also have this issue, cant get multiple mics to work. My layout id is 23 foe asrock b365 pro4.
> 
> Ports which I have:
> 
> * front combo jack (mic + headphone)
> * back line out
> * back line in
> * back mic in (doesn't work)
> 
> I've found out this is because of mutegpio, I set the mutegpio to a correct value for the front mic and then back mic doesn't work anymore. But haven't yet looked any further to fix it.

it may not be the same issue. My problem is that the layout settings corrected and the left microphone jack line in actually detected by OS. however, somehow the audio steam cannot be switched but still kept in built-in mic.

**Comment by Core-i99** [comment]
Mine shows in system preferences too, but no sound comes from it. 
If I set mutegpio to correct value for the node id of the back mic in then it does work but front one stops working.

**Comment by Sniki** [comment]
> > > 1. Yes. static noise fixed natively. no alcplugfix need.
> > > 2. sound outputs fully work in switch mode: automatic
> > >    
> > >    * left headphone jack (works)
> > >    * dock headphone jack (works)
> > >    * built-in speaker (works)
> > > 3. microphones (switch mode: automatic)
> > >    
> > >    * built-in mic. (works)
> > >    * dock microphone jack (works)
> > >    * left microphone jack. (not work)
> > > 
> > > The only bug is left microphone jack does not work currently.
> > 
> > 
> > Is it possible to leave laptop jack microphone working instead of the Dock one ? Just because not everyone may have a dock and people will tend to use more the laptop jack than the dock one with headsets that have microphone.
> 
> Not find the solution, yet. Probably I will look into this and try to make it next patch.

Have you tried booting without the dock and testing the laptop jack if microphone works on it.

If laptop jack mic works when laptop boots without dock attached then that is kinda perfect as not everyone does have a dock and it would be working perfectly fine already like that. Who uses the dock can simply use the dock jack anyway.

**Comment by hansyao** [comment]
> > > > 1. Yes. static noise fixed natively. no alcplugfix need.
> > > > 2. sound outputs fully work in switch mode: automatic
> > > >    
> > > >    * left headphone jack (works)
> > > >    * dock headphone jack (works)
> > > >    * built-in speaker (works)
> > > > 3. microphones (switch mode: automatic)
> > > >    
> > > >    * built-in mic. (works)
> > > >    * dock microphone jack (works)
> > > >    * left microphone jack. (not work)
> > > > 
> > > > The only bug is left microphone jack does not work currently.
> > > 
> > > 
> > > Is it possible to leave laptop jack microphone working instead of the Dock one ? Just because not everyone may have a dock and people will tend to use more the laptop jack than the dock one with headsets that have microphone.
> > 
> > 
> > Not find the solution, yet. Probably I will look into this and try to make it next patch.
> 
> Have you tried booting without the dock and testing the laptop jack if microphone works on it.
> 
> If laptop jack mic works when laptop boots without dock attached then that is kinda perfect as not everyone does have a dock and it would be working perfectly fine already like that. Who uses the dock can simply use the dock jack anyway.

unfortunately, neither it does not work without Dock.

**Comment by hansyao** [comment]
> Mine shows in system preferences too, but no sound comes from it. If I set mutegpio to correct value for the node id of the back mic in then it does work but front one stops working.

Thanks. I'll try set correct value of mutegpio to see the results later on.

**Comment by PMheart** [comment]
Hello! Is this still a WIP? I am sorry that I released v1.7.1 before asking for confirmation, but we will get this merged in the next release if further changes need to be made.

**Comment by hansyao** [comment]
> Hello! Is this still a WIP? I am sorry that I released v1.7.1 before asking for confirmation, but we will get this merged in the next release if further changes need to be made.

Yes. We can get this merged now. Any changes we can make it in the next release. thanks!

**Comment by PMheart** [comment]
OK, thanks for letting me know. I have withdrawn the v1.7.1 release, and will merge this later, then release a new one instead.

**Comment by PMheart** [comment]
Merged, thanks!

**Comment by hansyao** [comment]
> 

got it. thanks!

**Comment by Sniki** [comment]
Maybe Off-Topic but related to AppleALC in general.

@hansyao if you can fix this, i would like to know the links on where you learned how to patch Audio correctly, i have seen a bit sfrom your repo/sites you linked but in chinese (if i am correct). i had to translate to look at some ways how to figure out specific things into audio patching that no other guides have provided such informations.

In one word, it would be wise to make a How to correctly patch Audio Document into this repository so everyone can fix their codecs that are still incomplete (handicaped to be used with CodecCommander or ALCPlugFix).
There are also a lot of codecs that are actually the same but just share credits from a different user and different machine but listed 3-10 times where instead we could merge these into one patch and provide a supported list document / wiki for example:
ALC292 (ALC3232) is listed like more than 5 times / patched more than 5 times from different people and none of it is completely right, All of them have static noise without ALCPlugFix, Yours is the only one without that issue and i can also tell it should work 100% the same whether it's on a HP, Thinkpad, Dell or whatever laptop. tested all the ALC292 patches on my Thinkpads and pretty much they all work the same way.

It would be wise to audit the patches and merge the same ones into a single patch, list it on the Wiki/Support List doc like this:

Codec: ALC292 with Docking Station support 
Compatible/tested on: Lenovo Thinkpads T440,T440P,T440S,X240,L440, Dell Precision M4800, etc.
Layout ID: **
Credits: X, Y, Z

This would cleanup AppleALC a lot and have less confusion regarding current support.
I know some codecs share different configurations but at least i am sure that there are tons of them like i mentioned above.

**Comment by MacPeet** [comment]
@Sniki

Merging the different ID's alc292 makes no sense. Not every computer is the same and not every user needs to configure the docking station.
This ID 59 does not work on my Lenovo T450S. I just tested it with the latest Lilu/AppleALC. Speaker icon is gray in the menu bar.
My ID 15 ALC292 - for LENOVO THINKPAD T440_T450_X240 - ManualMode also works without CodecCommander and ALCPlugFix without problems.
Different ID's are good considering the many different computers.
Merging the ID's is not good.
As an example, look at alc269, many more different ID's, due to the many different computers.

**Comment by PMheart** [comment]
@hansyao This PR has been merged to 1.7.1 release.

See https://github.com/acidanthera/AppleALC/releases/tag/1.7.1 for more details.

**Comment by hansyao** [comment]
> @hansyao This PR has been merged to 1.7.1 release.
> 
> See https://github.com/acidanthera/AppleALC/releases/tag/1.7.1 for more details.

@PMheart  Not really. I just double checked that the binary https://github.com/acidanthera/AppleALC/releases/download/1.7.1/AppleALC-1.7.1-RELEASE.zip did not actually include the patches. ps. just uncomressed and checked `info.plist` which not include the new patches.  however, the [artifacts](https://github.com/acidanthera/AppleALC/suites/6161039049/artifacts/218150205) works well.

**Comment by MacPeet** [comment]
I loaded exactly this release (releases/tag/1.7.1) from the link, but the new ID 59 does not work with it.

**Comment by hansyao** [comment]
> @hansyao This PR has been merged to 1.7.1 release.
> 
> See https://github.com/acidanthera/AppleALC/releases/tag/1.7.1 for more details.

@PMheart  it seems the workflow actions run failed https://github.com/acidanthera/AppleALC/actions/runs/2184726481. the new built binary was not updated.

**Comment by hansyao** [comment]
> I loaded exactly this release (releases/tag/1.7.1) from the link, but the new ID 59 does not work with it.

@MacPeet you may try
https://github.com/acidanthera/AppleALC/suites/6161039049/artifacts/218150205

**Comment by MacPeet** [comment]
@hansyao

ok thanks, so my T450s works partly with ID59 (release AppleALC seems to be defective)

internal speaker works
internal mic works
SwitchMode HP (right side on laptop) works and HP works
HP Mic SwitchMode is not visible and not working

I don't have a docking station.

For my T450s, ID59 doesn't seem to be perfect.

I'm sticking with my ID 15 ManualMode as everything works there.

**Comment by PMheart** [comment]
> > @hansyao This PR has been merged to 1.7.1 release.
> > See https://github.com/acidanthera/AppleALC/releases/tag/1.7.1 for more details.
> 
> @PMheart it seems the workflow actions run failed https://github.com/acidanthera/AppleALC/actions/runs/2184726481. the new built binary was not updated.

Thanks for letting me know. I have triggered the build again; it should be ready within minutes as we have now fixed Coverity.

**Comment by hansyao** [comment]
> @hansyao
> 
> ok thanks, so my T450s works partly with ID59 (release AppleALC seems to be defective)
> 
> internal speaker works internal mic works SwitchMode HP (right side on laptop) works and HP works HP Mic SwitchMode is not visible and not working
> 
> I don't have a docking station.
> 
> For my T450s, ID59 doesn't seem to be perfect.
> 
> I'm sticking with my ID 15 ManualMode as everything works there.

May I know whether static noise avoid in your T450s when you applied layout id 59? And your HP mic is combo jack, right?

**Comment by hansyao** [comment]
> > > @hansyao This PR has been merged to 1.7.1 release.
> > > See https://github.com/acidanthera/AppleALC/releases/tag/1.7.1 for more details.
> > 
> > 
> > @PMheart it seems the workflow actions run failed https://github.com/acidanthera/AppleALC/actions/runs/2184726481. the new built binary was not updated.
> 
> Thanks for letting me know. I have triggered the build again; it should be ready within minutes as we have now fixed Coverity.
> 
> UPDATE - Done.

Well Noticed it’s now built successfully. 😏

**Comment by hansyao** [comment]
> @hansyao
> 
> I had no static noise on the HP on the T450s in my brief test with ID59 and yes it is a combo jack. HP-Mic does not work with it.
> 
> The problems with combo sockets in SwitchMode have been known for a long time and not only with alc292. One solution was CodecComander and ALCPlugFix, but not for me. I'm always looking for native solutions. That's why I developed ID15 ManualMode, no problems mit ID15, HP works without static noise, HP-Mic also works without CodecComander and ALCPlugFix.
> 
> No longer a problem for me anyway, I use AirPods 3rd Gen with T450s.

@macpeet That's sounds like pretty good for T450s in id15. unfortunately, id15 does not work for Dell M4800. that's why I used to developed id59 for it.

**Comment by hansyao** [comment]
> @hansyao
> 
> Yes, not every computer (manufacturer) is the same. That's the only reason I replied to Sniki's post " Merging ID's is not good ". The many different, but also almost identical IDs certainly make sense.
> 
> There are also differences between users with and without a docking station. The development of new ID's is therefore becoming more and more difficult and with the newer combo sockets anyway. Previously with separate sockets (HP/Mic) there were never any problems.

Yes. I agree with you. If we wanna do the merging id we may have to change the whole architecture in current AppleALC to  adopt the compatibility but not only update pin config and layout as currently we are doing. That would be very huge work and I don’t think it’s worth to do it now.

**Pull request merged**
