### PR TITLE
Add Realtek ALC289 layout-id 87 for Alienware m15

### PR DESCRIPTION
**Pull request by GitNaufal**

### CODE REVIEW

**Comment by jackjack1-su** [comment]
Plz remove the xml tag.

**Comment by GitNaufal** [comment]
> Plz remove the plist tag.

my last commits, its that true what you mean?

**Comment by jackjack1-su** [comment]
Yes.

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/AppleALC/pull/658/files#diff-a09a792cff0fe80f1d70ed67a5228fa240357d701fe77b7f3b8aff38c0feb4daR5296
Please build AppleALC in Xcode for fix info.plust structure (data).

**Comment by chunma26** [comment]
Add Realtek ALC887 layout-id 110 for MSI H110M Pro VH

[MSI H110M Pro VH.zip](https://github.com/acidanthera/AppleALC/files/6101644/MSI.H110M.Pro.VH.zip)

↑That has the Info.plist , layout110.xml ,Platforms110.xml and PinConfigs.kext

**Pull request merged**
