### PR TITLE
Add Codec Conexant CX20632 for HP EliteDesk

### PR DESCRIPTION
**Pull request by Halelluja12**

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Hi again!
Why are you truing to modify .gitignore?

**Comment by Halelluja12** [comment]
> Hi again!
> Why are you trying to modify .gitignore?

i dont know, haha :))

**Comment by vandroiy2013** [comment]
Please remove .gitignore modifications.

**Comment by Halelluja12** [comment]
> Please remove .gitignore modifications.

okey, i'll create pull request the last one :))

**Pull request closed without merging**
