### PR TITLE
Add Jack Sense and EAPD support to ALC230 layout 13 & 20 and add WakeConfigData to layout 13

### PR DESCRIPTION
**Pull request by Ab2774**
All thank goes to @fewtarius

### CODE REVIEW

**Comment by fewtarius** [comment]
Thanks @Ab2774, but I haven't been involved with this.  Since I'm looking at it though, why did you change two layouts and how did you test them?  Why did you also change the comments?  Did you talk with the original layout author(s) yet?  You should seek their approval, and also add more info about what you're changing and why you're changing it.

**Comment by Ab2774** [comment]
Hi @fewtarius, I did test them on both my Lenovo laptops (Kaby Lake and Ice Lake), I changed the comments because not just Lenovo IdeaPad 320 laptops come with ALC230, I don't mind a review from @andreszerocross and @maiconjs, usually, in order to gain function of headphones after sleep ALCPlugFix should be installed, however, with this fix it no longer requires, but unfortunately, there are still some issues that I haven't been able to fix as using mic after sleep make audio disappears for few mins, Chrome doesn't support mic until one of the channels is disabled through Audio MIDI Setup, and finally mic input level in System Preferences.
I'd really appreciate it if you have any idea how to fix these.
Cheers

**Comment by fewtarius** [comment]
> unfortunately, there are still some issues that I haven't been able to fix as using mic after sleep make audio disappears for few mins, Chrome doesn't support mic until one of the channels is disabled through Audio MIDI Setup, and finally mic input level in System Preferences.
> I'd really appreciate it if you have any idea how to fix these.
> Cheers

It sounds like you need to create a new layout and fix the issues specific to your codec implementation.  PRs aren't usually used for help, use the forums for that.

**Comment by Andrey1970AppleLife** [comment]
You shan't makes changes without coordination with the author of an original layout.
You need to create a new layout.

**Comment by Ab2774** [comment]
> You shan't makes changes without coordination with the author of an original layout.
> You need to create a new layout.

Hi, I do not mind making a new layout(s) but should all the existing users move to the new layout(s) and never fix the issues in the original layout in the first place?
Thanks

**Comment by vit9696** [comment]
@Andrey1970AppleLife I checked the changes and they look adequate, we did add similar codes for various other codecs in the past when `WakeConfigData` was only starting to be a thing. I am not sure these layouts are currently maintained by anyone, and I think it will be better to take the risks and merge the changes and revert them if they cause issues.

**Comment by fewtarius** [comment]
Since this was reopened I thought I'd take a closer look at it, hope you don't mind.

```
Codec 10EC 0230, layout 20
01271EA0 Mic in, Unknown
01471E17 Speaker, Other analog
01971E81 Line in, 1/8” jack
02171E21 HP out, 1/8” jack

01271C10 01271D00 01271EA0 01271F90 01471C20 01471D00 01471E17 01471F90 01470C02 01971C30 01971D10 01971E81 01971F04 01970C02 02171C40 02171D10 02171E2B 02171F04 01371C50 01371D00 01371E00 01371F40 01D71C60 01D71DB0 01D71E66 01D71F40

01470C02 02170C02 01970725
```

This one may need to be adjusted, as you're enabling EAPD on the mic (0x19), but not on the headphone output (0x21).  Might have better results if you remove 01970C02, and add 02170C02 at the end of node 21's configuration data.

```
Codec 10EC 0230, layout 13
01271EA0 Mic in, Unknown
01471E17 Speaker, Other analog
01971E81 Line in, 1/8” jack
02171E2B HP out, Combo Jack

01471C10 01471D01 01471E17 01471F90 01470C02 02171C20 02171D10 02171E21 02171F13 02170C02 01271C30 01271D01 01271EA0 01271F90 01971C40 01971D11 01971E81 01971F93

01470C02 02170C02 01970725
```

This one looks ok.

**Comment by Ab2774** [comment]
Hi @fewtarius, of course, I don't mind any improvements, if you can help with my other issues id really appreciate it if you're willing to, please continue on [InsanelyMac](https://www.insanelymac.com/forum/topic/345555-no-mic-after-sleep/) as this not usually a please for discussion and help.
Thanks a lot

**Pull request merged**
