### PR TITLE
NUC8I5BEH JUST MIC

### PR DESCRIPTION
**Pull request by frozenzero123**
nuc8i5beh retains the mic option and removes the 3.5 headphone jack, (the usage scenario is an external sound card and hdmi audio cable)

### CODE REVIEW

**Comment by frozenzero123** [comment]
@PMheart Solve, my nuc8 alc235 layouid88 release version is invalid, but it is ok to use the version I compiled before, please help me and see what's going on

**Comment by PMheart** [comment]
Hello! Is the latest 1.7.2 broken for you, while 1.7.1 worked?

**Comment by frozenzero123** [comment]
> Hello! Is the latest 1.7.2 broken for you, while 1.7.1 worked?
Although I don't want to say it, but because I compiled the lamp myself before, it was version 1.71, so I didn't test it.

**Comment by frozenzero123** [comment]
@PMheart Hope you guys can help me see what's going on

**Comment by PMheart** [comment]
Hello!

It turns out that you did not update https://github.com/acidanthera/AppleALC/blob/master/Resources/ALC235/Info.plist, thus your resource files were not detected by ResourceConverter.

Please file a PR again, or I can help fix it as well.

**Comment by frozenzero123** [comment]
@PMheart When you said that, I remembered! I seem to have forgotten this when I merged before! If possible, please help to adjust it! It's a bit of a waste of resources for me to ask for PR again!

**Comment by frozenzero123** [comment]
> Thanks for letting me know. It is done in master.

Thanks！

**Pull request merged**
