### PR TITLE
Add ALC289 layout-id 33 for Asus ROG Zephyrus G14

### PR DESCRIPTION
**Pull request by PIut02**
& fix layout-id 93 in xml

### CODE REVIEW

**Comment by Core-i99** [comment]
structure of alc289 info.plist is messed up

**Comment by PIut02** [comment]
Already fix it,sorry about that.

**Comment by ExtremeXT** [comment]
@PIut02 Is this the AMD model? Does your microphone work with your custom layout?

**Comment by PIut02** [comment]
> @PIut02 Is this the AMD model? Does your microphone work with your custom layout?

The microphone is not working, whether it is built-in or 3.5mm interface. I have only repaired the speaker of this model, so I guess it may not be a layout-id issue.

**Pull request closed without merging**
