### PR TITLE
Added CX20632 layout-id 20 for HP Elitedesk 800 G5 Mini by phucnguyen2411

### PR DESCRIPTION
**Pull request by phucnguyen2411**
Fix 2 headphone port + mic as Line In. 
Thanks.

### CODE REVIEW

**Comment by sisumara** [comment]
> Fix 2 headphone port + mic as Line In.

Hello

I just tried your layout with headset and found that microphone isn't working. After that I decided to check microphone input on Ubuntu 20 and there everything works as expected. 

Is there some mistake in layout configuration?

Thank you

**Comment by phucnguyen2411** [comment]
> > Fix 2 headphone port + mic as Line In.
> 
> Hello
> 
> I just tried your layout with headset and found that microphone isn't working. After that I decided to check microphone input on Ubuntu 20 and there everything works as expected.
> 
> Is there some mistake in layout configuration? Did you test microphone input?
> 
> Thank you

That was missing my patch, will push the latest code soon.

**Comment by sisumara** [comment]
Great! Thank you for feedback.

**Comment by rafale77** [comment]
Any update on this?

**Comment by phucnguyen2411** [comment]
dont have time to look at this. Will try sometime.

**Comment by taotaolin** [comment]
my microphone isn't working Any update on this?

**Pull request merged**
