### PR TITLE
Add CX8050 layout 13 for ASUS S410U/X411U by cowpod

### PR DESCRIPTION
**Pull request by cowpod**
Fix internal mic and linein/external mic, adjust boost, adjust VREF

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Hi
You broke XML structure in pinconfig info.plist 
Fix it please

**Comment by cowpod** [comment]
hi, fixed

**Comment by vandroiy2013** [comment]
> hi, fixed

Not fixed!
XML structure is broken 
Build project in Xcode before making PR

**Comment by vandroiy2013** [comment]
Added 
Thanks

**Pull request merged**
