### PR TITLE
Added ALC294 layout-id 44 for ASUS UX534FAC by narcyzzo

### PR DESCRIPTION
**Pull request by narcyzzo**
- Fixed Internal Speakers not working at all
- Fixed Internal Speakers not working after reboot from Windows with Realtek Driver installed
- Fixed Microphone
- Again Huge Thanks to @mikebeaton

### CODE REVIEW

**Comment by radiolip** [comment]
Hello! I just tested this layout, on ASUS UX534FTC / i7-10510U. Working like a charm, finally Speakers are playing sound on this codec! Great job. Thank you!

**Comment by frozenzero123** [comment]
> * Fixed Internal Speakers not working after reboot from Windows with Realtek Driver installed
how did you fix it？

**Comment by narcyzzo** [comment]
> > * Fixed Internal Speakers not working after reboot from Windows with Realtek Driver installed
> >   how did you fix it？
> 
Hello! u should read this https://github.com/acidanthera/AppleALC/pull/758 
Better Write up will come soon.

**Comment by mikebeaton** [comment]
Hi - Script and write-up here: https://github.com/mikebeaton/dump-coeff . Feedback welcome.

**Comment by mikebeaton** [comment]
`dump_coeff.sh` now part of AppleALC https://github.com/acidanthera/AppleALC/commit/02983ded485f3259b42f866de5140ae56e0d34b3 with write-up at https://github.com/acidanthera/AppleALC/wiki/Dumping-processing-coefficients .

**Comment by narcyzzo** [comment]
Hello @nikstar glad to hear u guys take profits from us work. Sorry for late respond, i have sended your commands, everything works, but i dont know if modyfying my layout to add another device, or adding completely new layout is better idea? cc @mikebeaton

**Comment by mikebeaton** [comment]
I guess if it works for you @narcyzzo and makes the layout work for @nikstar too, then it might as well be in one layout. If anyone else using it reports a problem after this change, you could split.

@nikstar, just to confirm, you had the situation where you had the visible sliders etc. but no sound, and then with these additional tweaks, you got sound, right? (So hopefully, at worst, someone else with the combined layout could see that it is nearly right, and can do some more tweaking themselves.)

**Comment by nikstar** [comment]
> just to confirm, you had the situation where you had the visible sliders etc. but no sound, and then with these additional tweaks, you got sound, right? 

Yes, exactly. 

I'll create the PR then. Thanks for checking, @narcyzzo

**Pull request merged**
