### PR TITLE
Add support for legacy Macs

### PR DESCRIPTION
**Pull request by khronokernel**
With macOS Mojave, many layouts were dropped that were used by older Macs. This PR is meant to add support back in for those models so the legacy Mac community no longer needs to use old versions of AppleHDA.

Currently a few models are missing from our database so unsure what layout ID these models used:

* Macmini4,1
* Macmini5,3
* iMac7,1 24"
* iMac8,1 20"
* iMac9,1 24"
* iMac11,3

Will also add RTL885 support for the remaining Mac models such as MacPro3,1

### CODE REVIEW

**Comment by khronokernel** [comment]
Currently working with Intel based chipset Macs, Nvidia based Macs need more testing

**Comment by Andrey1970AppleLife** [comment]
You haven't added PinConfigs.

**Comment by khronokernel** [comment]
@Andrey1970AppleLife Big Sur's AppleHDAHardwareConfigDriver hasn't had any of the ConfigData removed for older codecs, if in future releases of macOS Apple does remove them we'll add them to PinConfig.kext

**Comment by vit9696** [comment]
Yeah, looks good to me. Please include this in the next release.

**Pull request merged**
