### PR TITLE
Rename 400 series LP controller, add 400 series PCH-H controller

### PR DESCRIPTION
**Pull request by fewtarius**
Adds the PCH-H Comet Lake PCH-H controller.

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Hi
Did you test it?

**Comment by fewtarius** [comment]
Did not, I don't have that hardware.  I found the PCI ID in the [Linux kernel source](https://github.com/torvalds/linux/blob/master/sound/soc/sof/sof-pci-dev.c#L427) while troubleshooting ALC284 / Comet Lake 02c8 audio problems on my laptop and cross-referenced it with a PCI device database.  Thought submitting it would be helpful.

**Comment by vit9696** [comment]
@vandroiy2013 we can merge it and wait anybody to report problems? An alternative would be to leave that open until somebody with the hardware appears. I do not mind either, the patch seems likely to be needed in any case.

**Comment by R3TLIX** [comment]
I have a commet lake laptop Dell with i5-10210U. My codec is ALC3204 but there is no support for it. Some people say its same as ALC236. I tried all the layouts for ALC236 but couldnt get audio working. I tried everything possible. I don't know if the problem is my codec just not aupported or because the chipset is 400 series. Can you please add support for ALC3204, I can provide the information needed (I have the codec dump from Linux). I would really appreciate that and I would love to help because I know a few more people with the same laptop who didnt get audio to work. Also sorry if thats not the right place to ask this question.

**Comment by fewtarius** [comment]
@R3TLIX a pull request is not the appropriate place to ask for support.  Comet Lake audio isn't working for many of us at the moment, even with a custom layout.

**Pull request merged**
