### PR TITLE
Fixed Jack Sense and EAPD on ALC 236 layout ID 14

### PR DESCRIPTION
**Pull request by erinviegas**
Changed Path Map ID to 14 and added missing Wake verb. This layout now works without any Jack fix or verbstub kext.

### CODE REVIEW

**Comment by Lorys89** [comment]
> Cambiato l'ID mappa del percorso a 14 e aggiunto il verbo Wake mancante. Questo layout ora non funziona senza alcuna correzione di Jack o verbstub kext.



> Changed Path Map ID to 14 and added missing Wake verb. This layout now works without any Jack fix or verbstub kext.

Does the combojack work with alc 236?

**Comment by erinviegas** [comment]
> Does the combojack work with alc 236? the headphone part fills me but the headphone microphone no, I don't use verbstub or codecommander
Yes, it works fine.

**Comment by Lorys89** [comment]
> > Does the combojack work with alc 236? the headphone part fills me but the headphone microphone no, I don't use verbstub or codecommander
> 
> Yes, it works fine.

even the headset microphone? 
if you, kext mail compiled, and I try it.

**Comment by Lorys89** [comment]
> > Does the combojack work with alc 236? the headphone part fills me but the headphone microphone no, I don't use verbstub or codecommander
> 
> Yes, it works fine.

i compiled and tested your kext, and the combojack comes out headphone sound but headphone mic doesn't work

**Comment by erinviegas** [comment]
> i compiled and tested your kext, and the combojack comes out headphone sound but headphone mic doesn't work
It works as Line In for me. What I have done is specific to Lenovo 330S. Maybe try a different layout ID for yourself.

**Comment by Lorys89** [comment]
> > i compiled and tested your kext, and the combojack comes out headphone sound but headphone mic doesn't work
> 
> It works as Line In for me. What I have done is specific to Lenovo 330S. Maybe try a different layout ID for yourself.

please, send me your codec dump

**Comment by Vorshim92** [comment]
> > i compiled and tested your kext, and the combojack comes out headphone sound but headphone mic doesn't work
> 
> It works as Line In for me. What I have done is specific to Lenovo 330S. Maybe try a different layout ID for yourself.

hi man! thanks for your support with this layout14... may I ask too your codecdump? just to learn everything about it! I want to try and make a new layout for my dell and yours it's a pretty good start 👍

**Comment by erinviegas** [comment]
> hi man! thanks for your support with this layout14... may I ask too your codecdump? just to learn everything about it! I want to try and make a new layout for my dell and yours it's a pretty good start 👍

@Vorshim92 here you go. I still have issues when connecting Bluetooth devices. The audio is muffled when the input is set to the Bluetooth headphones. Maybe someone can come up with a fix.
[HdaCodec (Realtek ALC236).txt](https://github.com/acidanthera/AppleALC/files/5785540/HdaCodec.Realtek.ALC236.txt)

**Pull request merged**
