### PR TITLE
niladrihere - Realtek ALC255 for Acer Nitro AN515-51 : Layout 78

### PR DESCRIPTION
**Pull request by niladrihere**
Kindly review and accept my pr.

### CODE REVIEW

**Comment by alessiomatricardi** [comment]
Hi @niladrihere, I have one similar laptop (Acer Swift 3) with ALC255. Also pins config is the same compared to mine. Is this your specific codec? If yes, were you able to get the headset's microphone to work with this layout?
Schermata 2020-11-12 alle 01 42 30

**Comment by armenio** [comment]
> Hi @niladrihere, I have one similar laptop (Acer Swift 3) with ALC255. Also pins config is the same compared to mine. Is this your specific codec? If yes, were you able to get the headset's microphone to work with this layout?
> Schermata 2020-11-12 alle 01 42 30

Try layout 86 (0x56 in hex)

**Comment by alessiomatricardi** [comment]
> > Hi @niladrihere, I have one similar laptop (Acer Swift 3) with ALC255. Also pins config is the same compared to mine. Is this your specific codec? If yes, were you able to get the headset's microphone to work with this layout?
> > Schermata 2020-11-12 alle 01 42 30
> 
> Try layout 86 (0x56 in hex)

I tried, it works as well as layout 3, but headset mic doesn't work in both

**Comment by niladrihere** [comment]
> Hi @niladrihere, I have one similar laptop (Acer Swift 3) with ALC255. Also pins config is the same compared to mine. Is this your specific codec? If yes, were you able to get the headset's microphone to work with this layout?
> Schermata 2020-11-12 alle 01 42 30

Sadly no I wasn't able to get my headphone mic working !

**Comment by niladrihere** [comment]
> > Hi @niladrihere, I have one similar laptop (Acer Swift 3) with ALC255. Also pins config is the same compared to mine. Is this your specific codec? If yes, were you able to get the headset's microphone to work with this layout?
> > Schermata 2020-11-12 alle 01 42 30
> 
> Try layout 86 (0x56 in hex)

Headphone Mic doesn't works !

**Comment by niladrihere** [comment]
> Hi @niladrihere, I have one similar laptop (Acer Swift 3) with ALC255. Also pins config is the same compared to mine. Is this your specific codec? If yes, were you able to get the headset's microphone to work with this layout?
> Schermata 2020-11-12 alle 01 42 30

Hey does your headphone mic work with Acer Swift 3?

**Comment by armenio** [comment]
> > > Hi @niladrihere, I have one similar laptop (Acer Swift 3) with ALC255. Also pins config is the same compared to mine. Is this your specific codec? If yes, were you able to get the headset's microphone to work with this layout?
> > > Schermata 2020-11-12 alle 01 42 30
> > 
> > 
> > Try layout 86 (0x56 in hex)
> 
> I tried, it works as well as layout 3, but headset mic doesn't work in both

right? that works without any dependency(CodecComander/AlcPlugFix) here.

**Comment by alessiomatricardi** [comment]
> > > > > Hi @niladrihere, I have one similar laptop (Acer Swift 3) with ALC255. Also pins config is the same compared to mine. Is this your specific codec? If yes, were you able to get the headset's microphone to work with this layout?
> > > > > Schermata 2020-11-12 alle 01 42 30
> > > > 
> > > > 
> > > > Try layout 86 (0x56 in hex)
> > > 
> > > 
> > > I tried, it works as well as layout 3, but headset mic doesn't work in both
> > 
> > 
> > right? that works without any dependency(CodecComander/AlcPlugFix) here.
> 
> Hey could you share your codec dump ?

idk if the question was for me, but...
[codec_dump.txt](https://github.com/acidanthera/AppleALC/files/5538610/codec_dump.txt)

**Comment by niladrihere** [comment]
> > > > > > Hi @niladrihere, I have one similar laptop (Acer Swift 3) with ALC255. Also pins config is the same compared to mine. Is this your specific codec? If yes, were you able to get the headset's microphone to work with this layout?
> > > > > > Schermata 2020-11-12 alle 01 42 30
> > > > > 
> > > > > 
> > > > > Try layout 86 (0x56 in hex)
> > > > 
> > > > 
> > > > I tried, it works as well as layout 3, but headset mic doesn't work in both
> > > 
> > > 
> > > right? that works without any dependency(CodecComander/AlcPlugFix) here.
> > 
> > 
> > Hey could you share your codec dump ?
> 
> idk if the question was for me, but...
> [codec_dump.txt](https://github.com/acidanthera/AppleALC/files/5538610/codec_dump.txt)

is your headphone mic working ? If yes provide the layout id

**Comment by alessiomatricardi** [comment]
> > > > > > > Hi @niladrihere, I have one similar laptop (Acer Swift 3) with ALC255. Also pins config is the same compared to mine. Is this your specific codec? If yes, were you able to get the headset's microphone to work with this layout?
> > > > > > > Schermata 2020-11-12 alle 01 42 30
> > > > > > 
> > > > > > 
> > > > > > Try layout 86 (0x56 in hex)
> > > > > 
> > > > > 
> > > > > I tried, it works as well as layout 3, but headset mic doesn't work in both
> > > > 
> > > > 
> > > > right? that works without any dependency(CodecComander/AlcPlugFix) here.
> > > 
> > > 
> > > Hey could you share your codec dump ?
> > 
> > 
> > idk if the question was for me, but...
> > [codec_dump.txt](https://github.com/acidanthera/AppleALC/files/5538610/codec_dump.txt)
> 
> is your headphone mic working ? If yes provide the layout id

Nope, i use layout 29 and headphone mic doesn't work. Also with layout 86 nothing change.

**Comment by niladrihere** [comment]
> > > > > > > > Hi @niladrihere, I have one similar laptop (Acer Swift 3) with ALC255. Also pins config is the same compared to mine. Is this your specific codec? If yes, were you able to get the headset's microphone to work with this layout?
> > > > > > > > Schermata 2020-11-12 alle 01 42 30
> > > > > > > 
> > > > > > > 
> > > > > > > Try layout 86 (0x56 in hex)
> > > > > > 
> > > > > > 
> > > > > > I tried, it works as well as layout 3, but headset mic doesn't work in both
> > > > > 
> > > > > 
> > > > > right? that works without any dependency(CodecComander/AlcPlugFix) here.
> > > > 
> > > > 
> > > > Hey could you share your codec dump ?
> > > 
> > > 
> > > idk if the question was for me, but...
> > > [codec_dump.txt](https://github.com/acidanthera/AppleALC/files/5538610/codec_dump.txt)
> > 
> > 
> > is your headphone mic working ? If yes provide the layout id
> 
> Nope, i use layout 29 and headphone mic doesn't work. Also with layout 86 nothing change.

same here

**Comment by alessiomatricardi** [comment]
Some time ago I asked on InsanelyMac but nobody replied me

**Comment by vandroiy2013** [comment]
Closed because this is not a chat and i can't review pull request because of this off-topic. 

@niladrihere,  Please when you'll have final version of your layout open new pull request and make it clean. 
Also don't forget to build project in Xcode to make proper XML formatting in info.plist files. 
Thanks!

**Pull request closed without merging**
