### PR TITLE
add ALC289 ID15 for Dell 7730 Precision CM240 by MacPeet

### PR DESCRIPTION
**Pull request by MacPeet**
everything works, internal speakers, internal mic, HP and mic on combination connection

### CODE REVIEW

**Comment by Andrey1970AppleLife** [comment]
Delete plist tags from xml.

**Comment by MacPeet** [comment]
@ Andrey1970AppleLife

I do not understand. What did I do wrong (Delete plist tags from xml)? I haven't done a pull in a long time and Github has a lot of new features, as I had to see. Please state exactly what to do if my pull is wrong.

**Comment by Andrey1970AppleLife** [comment]
Look here:
https://github.com/acidanthera/AppleALC/commit/a6a6a142a95487a31fe434eb8941fc589eace4f6

**Comment by MacPeet** [comment]
very funny, I haven't changed this thing
I created a new fork normally, then clone, then integrated new codec, then build, then pull
In my fork / clone only my changes with M or A were displayed before the PullRequest. So what should i do?

Your link shows master 1.5.8 above, but the source code here is currently 1.5.9. Is it really my fault?

**Comment by Andrey1970AppleLife** [comment]
You added two xml files.

**Comment by MacPeet** [comment]
Yes, of course, layout15. xml and Platforms15.xml for the new layoutID 15 codec for alc289. Now where is the mistake? Both are needed, or has something changed?

**Comment by Andrey1970AppleLife** [comment]
Delete plist tags from xml files. You see an example https://github.com/acidanthera/AppleALC/pull/662#issuecomment-798961578

**Comment by usr-sse2** [comment]
> Yes, of course, layout15. xml and Platforms15.xml for the new layoutID 15 codec for alc289. Now where is the mistake? Both are needed, or has something changed?
> All 4 files changed are only green. No entries are deleted. Everything as always when adding a new codec. I really don't understand where I am making a mistake. Sorry

To reduce size, we have deleted the
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
```
and
```xml
</plist>
```
tags from all XML files and require all contributors to do the same when adding a new codec. You haven't yet done it in your added files. Please remove these lines from `layout15.xml` and `Platforms15.xml`.

**Comment by MacPeet** [comment]
Sorry, I haven't made a PullRequest in a long time. This reduction was new to me. Now I understand, thank you. Is the change ok, or should I close the pull and do it again? Thank you for your help!

**Comment by Andrey1970AppleLife** [comment]
Ok

**Pull request merged**
