### PR TITLE
[PATCH] Apply Wern Apfel patch to CX8050

### PR DESCRIPTION
**Pull request by vasishath**
Fixes speaker volume slider on Asus Vivobook X510UNR

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Hi. 
Did you speak with Wern Apfel about this changes?

**Comment by vasishath** [comment]
Hey
No i didnt. I just saw the AppleALC thread on insanelymac and found a user facing same issue with CX8051. So i suspected this and compiled it with the changes myself and found it fixed.

**Comment by vandroiy2013** [comment]
OK. Thanks. Merged

**Comment by vasishath** [comment]
Thanks a lot :)

**Pull request merged**
