### PR TITLE
Moving armênio ALC255 Layout ID 7 to 86, and add ALC257 Layout ID 86

### PR DESCRIPTION
**Pull request by armenio**
To avoid confusion with Layout ID 7 already reserved

Also:
- Removed DspFunctions (unknown)
- Removed unnecessary patch

[ .patch](https://patch-diff.githubusercontent.com/raw/acidanthera/AppleALC/pull/552.patch)
[.diff](https://patch-diff.githubusercontent.com/raw/acidanthera/AppleALC/pull/552.diff)

### CODE REVIEW

**Comment by Andrey1970AppleLife** [comment]
Don't delete Layout 7, simply add Layout 86, because it will be broken at those by whom Layout 7 uses.

**Comment by armenio** [comment]
> Don't delete Layout 7, simply add Layout 86, because it will be broken at those by whom Layout 7 uses.

Hi @Andrey1970AppleLife. 
it's the same layout. It was created recently by me and I was just changing his ID.
Because now i needed to create a new layout for another codec (ALC257), I see that I was using an ID already reserved for ALC255.
If there is no problem with keeping this ID 7, I don't see the necessity to create an another ID, I can just keep this one and send another pull request with necessary adjustments.

that's better?

**Comment by vandroiy2013** [comment]
@armenio You did right. Layouts from 1 to 10 are reserved for @mirone and @toleda resources. Will be merged in next release.

**Comment by armenio** [comment]
Thanks

**Comment by armenio** [comment]
> @armenio You did right. Layouts from 1 to 10 are reserved for @Mirone and @toleda resources. Will be merged in next release.

@vandroiy2013 can you, please, confirm that layout 86 for ALC257 will be merged too?

I wish I had sent 2 PR to get more clarified. However, I made a mistake during the commits and it seems to me that the two changes (changing ALC255 and adding ALC257) are here in the same PR.

Thank you

**Pull request merged**
