### PR TITLE
ALC269 added layout 91 (Chuwi CoreBox)

### PR DESCRIPTION
**Pull request by Luca1991**
Hi all, 
this PR adds layout 91 in ALC296 codec.
Using this layout both green (output) and red (input/microphone) jacks of Chuwi CoreBox are working perfectly.
This is based on my own codec dump (using ubuntu), but I took inspiration by layout 28 for the "signal processing" part.

Thank you,
Luca

### CODE REVIEW

**Comment by Andrey1970AppleLife** [comment]
You have to add pinconfig.

**Comment by Luca1991** [comment]
@Andrey1970AppleLife thank you for your reply. Please can you tell me how I can write a good entry in pinconfig? Reading the wiki, I wasn't able to figure out what I'm supposed to add to that file.
I'll do this ASAP if you can point me to the right direction.

**Comment by ipoa** [comment]
@Andrey1970AppleLife When compiling appleALC, it will report'mach/mach_types.h' file not found. How to configure it?

**Comment by Luca1991** [comment]
@Andrey1970AppleLife done! Proper pingconfig added to this PR!

Let me know if this is mergiable now or if I should add something else ;)

Thanks,
Luca

**Comment by ipoa** [comment]
@Luca1991 When compiling appleALC, it will report'mach/mach_types.h' file not found. How to configure it?

**Comment by Luca1991** [comment]
> @Luca1991 When compiling appleALC, it will report'mach/mach_types.h' file not found. How to configure it?

Hello mate, sorry but my PR is not a support thread. You should ask these questions in forums.

That said, this project is compiling fine for everyone else, so this os surely an issue on your end.

Make sure you have both lilu.kext (debug) and the latest MacKernelSDK (from acidanthera) in the same directory with the source code, and it should compile.

**Comment by ipoa** [comment]
@Luca1991 Thank you for your prompt. The problem has been solved.

**Pull request merged**
