### PR TITLE
Yoga s740 14IIL ice lake External mic solution (using 3.5 headset microphone)

### PR DESCRIPTION
**Pull request by frozenzero123**
Because s740 is "intel sst" built-in mic; so by setting the sound output to manual mode (to switch headphone output and speaker output), use the external headphone port mic as audio Input. Hope it can be submitted for approval
*Sorry I seem to upload the wrong way (first upload)

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Hi. You broke XML structure. Build project in Xcode before making PR

**Comment by frozenzero123** [comment]
> 嗨。你打破了XML结构。在制作公关之前，在Xcode中构建项目



> Hi. You broke XML structure. Build project in Xcode before making PR
[s740 id88 替换.zip](https://github.com/acidanthera/AppleALC/files/7552688/s740.id88.zip)


Ok, I will try again because I always fail to compile here, so I found someone to compile it before(Always report an error: "1 error generated.
Command AnalyzeShallow failed with a nonzero exit code")
Here is my source file. If you have time, can you test it for help me?

**Comment by frozenzero123** [comment]
> Hi. You broke XML structure. Build project in Xcode before making PR

Hello, I have tested it and it can be compiled successfully
[AppleALC-1.6.7-DEBUG.zip](https://github.com/acidanthera/AppleALC/files/7554526/AppleALC-1.6.7-DEBUG.zip)

**Comment by vandroiy2013** [comment]
One more time! BEFORE making pull request you have to build project in Xcode to fix XML structure you've broke!

**Comment by frozenzero123** [comment]
> One more time! BEFORE making pull request you have to build project in Xcode to fix XML structure you've broke!

ok I will do it , create a new Pull requests

**Pull request closed without merging**
