### PR TITLE
Improvements for ALC230 layout 20 and added layout 20 for ALC883 by samcabral

### PR DESCRIPTION
**Pull request by samcabral**
Changes in ALC230

- Removed Headset_dBV to fix noise in headphones
- Changed MuteGPIO in LineIn to match PinComplex 25 (0x19)
- Changed Boost in NodeID 25 to adjust input gain for external mic
- Input gain for internal mic remains the same as my previous PR

Volume 88%
Audio Track 1 - Internal Mic
Audio Track 2 - External Mic

Boost 1

Boost 1

Boost 3

Boost 3

EDIT

[codec_dump.txt](https://github.com/acidanthera/AppleALC/files/8052580/codec_dump.txt)

### CODE REVIEW

**Review by maiconjs — APPROVED** [review]

**Comment by samcabral** [comment]
Please let me know if the last commit is not good enough.

Works in Huananzhi X79G.

[codec_dump.txt](https://github.com/acidanthera/AppleALC/files/8113161/codec_dump.txt)

photo_2022-02-21 22 13 51

photo_2022-02-21 22 13 46

**Comment by Andrey1970AppleLife** [comment]
> Changes in ALC883
> 
> * Changed Boost for mics
> * Added Boost 3 for Line In
> * Added MuteGPIO and SignalProcessing for LineIn and Mic
> 
> Works in Huananzhi X79G.

Don't change layout 7, сreate new layout for ALC883. Otherwise PR will be closed.

**Comment by samcabral** [comment]
I will send another commit late.

**Comment by samcabral** [comment]
I will send another commit later.

**Comment by samcabral** [comment]
I added a new layout as requested.

It works.

Captura de Tela 2022-02-23 às 23 12 01

**Comment by meloay** [comment]
I added a new layout as requested.
layout-id 72
ALC235 for Lenovo M920x by meloay
截屏2022-03-10 11 10 30
截屏2022-03-10 11 11 00
[Artifacts.zip](https://github.com/acidanthera/AppleALC/files/8219959/Artifacts.zip)
[codec#0.txt](https://github.com/acidanthera/AppleALC/files/8219960/codec.0.txt)

**Comment by samcabral** [comment]
@meloay you need to send PR to add your layout.

**Pull request merged**
