### PR TITLE
Add LayoutID 69 [for MSI GF63 Thin 9SEXR] - Codec ALC269 by Vorshim92

### PR DESCRIPTION
**Pull request by Vorshim92**

### CODE REVIEW

**Comment by chadify** [comment]
@Vorshim92 I'm trying to build AppleALC using xcode 12.5 but it results in build error` mach/mach_types.h' file not found`. I'm also using MacKernelSDK.

**Comment by Vorshim92** [comment]
> @Vorshim92 I'm trying to build AppleALC using xcode 12.5 but it results in build error` mach/mach_types.h' file not found`. I'm also using MacKernelSDK. 

Send a screenshot of the folder

**Comment by chadify** [comment]
[Here](https://filebin.redpill-linpro.com/c0d3iueq82r5pgkr).

**Comment by Vorshim92** [comment]
> @Vorshim92 [Here](https://filebin.redpill-linpro.com/c0d3iueq82r5pgkr).

lilu kext is the debug version? try using this "xcodebuild -configuration Release" from the terminal

**Comment by chadify** [comment]
@Vorshim92 yes I'm using the debug version of lilu. I tried building from the terminal, still the same error.

**Pull request merged**
