### PR TITLE
Add [MSI] (0x1462) LayoutID 19 of Realtek ALC662 rev3.

### PR DESCRIPTION
**Pull request by wy414012**
- Customized based on MSI x79 motherboard.

### CODE REVIEW

**Comment by vandroiy2013** [comment]
"MSI" what? Please fix description and determine full device name and model.

**Comment by wy414012** [comment]
The description has now been corrected.

**Comment by Andrey1970AppleLife** [comment]
Delete plist tags from xml.

**Comment by wy414012** [comment]
Thanks for pointing out the error, which has been corrected.

**Comment by vandroiy2013** [comment]
Merged manually.

**Pull request closed without merging**
