### PR TITLE
LayoutID 98 for ALC897 in MSI PRO B760M-P

### PR DESCRIPTION
**Pull request by liangyi9812**
Add ALC897 for MSI PRO B760M-P by liangyi

### CODE REVIEW

**Comment by liangyi9812** [comment]
I'm not sure if this issue is related to this code.

panic(cpu 8 caller 0xffffff80153e0a79): [kalloc.type.var5.16]: element modified after free (off:0, val:0x0000000000000001, sz:16, ptr:0xffffff86a54da3c0)
    0: 0x0000000000000001
    8: 0x0000000000008040
Panicked task 0xffffff9509ad0258: 214 threads: pid 0: kernel_task
Backtrace (CPU 8), panicked thread: 0xffffff99d4cf9598, Frame : Return Address
0xffffffe45493ef00 : 0xffffff8014c7207d mach_kernel : _handle_debugger_trap + 0x4ad
0xffffffe45493ef50 : 0xffffff8014dc6164 mach_kernel : _kdp_i386_trap + 0x114
0xffffffe45493ef90 : 0xffffff8014db5c77 mach_kernel : _kernel_trap + 0x3b7
0xffffffe45493efe0 : 0xffffff8014c12951 mach_kernel : _return_from_trap + 0xc1
0xffffffe45493f000 : 0xffffff8014c7235d mach_kernel : _DebuggerTrapWithState + 0x5d
0xffffffe45493f0f0 : 0xffffff8014c71a07 mach_kernel : _panic_trap_to_debugger + 0x1a7
0xffffffe45493f150 : 0xffffff80153db40b mach_kernel : _panic + 0x84
0xffffffe45493f240 : 0xffffff80153e0a79 mach_kernel : ___smr_tail_invalid + 0x2433
0xffffffe45493f6a0 : 0xffffff8014cdf8f1 mach_kernel : _workload_config_available + 0x5181
0xffffffe45493f700 : 0xffffff8014c804e1 mach_kernel : _kalloc_ext + 0x131
0xffffffe45493f720 : 0xffffff7fa9ae2277 com.apple.driver.DspFuncLib : __ZN11CmhBEAMproc15allocate_memoryEv + 0x2f9
0xffffffe45493f760 : 0xffffff7fa9ae1ea1 com.apple.driver.DspFuncLib : __ZN11CmhBEAMproc10initializeEi + 0x79
0xffffffe45493f790 : 0xffffff7fa9ae1dd9 com.apple.driver.DspFuncLib : __ZN11CmhBEAMproc8validateEiiii + 0x2b
0xffffffe45493f7c0 : 0xffffff7fa9adc88b com.apple.driver.DspFuncLib : __ZN7CmhBEAM10initializeEiiiiiii + 0x22b
0xffffffe45493f810 : 0xffffff7fa9adb756 com.apple.driver.DspFuncLib : __ZN11DspLibBeam211resetmhBEAMEv + 0xc2
0xffffffe45493f860 : 0xffffff7fa9ada2f6 com.apple.driver.DspFuncLib : __ZN12DspFuncBeam24initEv + 0x6a
0xffffffe45493f880 : 0xffffff7fa9a724cc com.apple.driver.DspFuncLib : __ZN14DspFuncFactory13createDspFuncEPK8OSStringP14DspFuncManager + 0x50c
0xffffffe45493f8b0 : 0xffffff7fa9a92995 com.apple.driver.DspFuncLib : __ZN14DspFuncManager20addDspFunctionCalledEP8OSString + 0x37
0xffffffe45493f900 : 0xffffff7fa9a92cbb com.apple.driver.DspFuncLib : __ZN14DspFuncManager31addDspFunctionWithNameAndNumberEP8OSStringj + 0x35
0xffffffe45493f930 : 0xffffff7fa9a9454f com.apple.driver.DspFuncLib : __ZN14DspFuncManager27setParametersFromDictionaryEP12OSDictionary + 0x1af
0xffffffe45493f9c0 : 0xffffff7fa99a858a com.apple.driver.AppleHDA : __ZN14AppleHDAEngine30configureDSPForAppleHDAPathSetEP15AppleHDAPathSetb + 0xbe8
0xffffffe45493fa60 : 0xffffff7fa99a7262 com.apple.driver.AppleHDA : __ZN14AppleHDAEngine4initEP9IOServiceP13AppleHDACodecP12OSDictionaryP7OSArrayS7_iPv + 0xdf4
0xffffffe45493fb40 : 0xffffff7fa999ddfd com.apple.driver.AppleHDA : __ZN14AppleHDADriver22createAudioInputEngineEP7OSArrayi + 0x9b
0xffffffe45493fb90 : 0xffffff7fa999d040 com.apple.driver.AppleHDA : __ZN14AppleHDADriver18createAudioEnginesEP7OSArray + 0x3ca
0xffffffe45493fc10 : 0xffffff7fa9998c62 com.apple.driver.AppleHDA : __ZN14AppleHDADriver18initHardwareActionEP9IOService + 0x324
0xffffffe45493fc70 : 0xffffff8015314f58 mach_kernel : __ZN13IOCommandGate9runActionEPFiP8OSObjectPvS2_S2_S2_ES2_S2_S2_S2_ + 0xa8
0xffffffe45493fcd0 : 0xffffff7fa9998930 com.apple.driver.AppleHDA : __ZN14AppleHDADriver12initHardwareEP9IOService + 0x3c
0xffffffe45493fcf0 : 0xffffff7faa8a9f0f com.apple.iokit.IOAudioFamily : __ZN13IOAudioDevice5startEP9IOService + 0x10b
0xffffffe45493fd30 : 0xffffff7fa999a725 com.apple.driver.AppleHDA : __ZN14AppleHDADriver13completeStartEv + 0x183
0xffffffe45493fed0 : 0xffffff7fa999a3df com.apple.driver.AppleHDA : __ZN14AppleHDADriver11startActionEv + 0xff
0xffffffe45493ff40 : 0xffffff801531209e mach_kernel : __ZN10IOWorkLoop9runActionEPFiP8OSObjectPvS2_S2_S2_ES1_S2_S2_S2_S2_ + 0x3e
0xffffffe45493ff80 : 0xffffff7fa999a295 com.apple.driver.AppleHDA : __ZN14AppleHDADriver23handleAsynchronousStartEPv + 0x43
0xffffffe45493ffa0 : 0xffffff8014c1219e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         com.apple.iokit.IOAudioFamily(440.2)[626EA2F4-ED14-3987-AEEE-C183C95B4731]@0xffffff7faa8a6000->0xffffff7faa8c3fff
            dependency: com.apple.vecLib.kext(1.2.0)[AE5EFF10-F32C-3F4D-90D2-5C762C4E0519]@0xffffff7faaf3b000->0xffffff7faaffcfff
         com.apple.driver.DspFuncLib(440.2)[A199D19B-2689-3DFF-B461-A5956BC976ED]@0xffffff7fa9a71000->0xffffff7fa9b53fff
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[F8DA24BC-B401-36FF-8ED1-2BABE80EA0C5]@0xffffff8016024000->0xffffff801602dfff
            dependency: com.apple.iokit.IOAudioFamily(440.2)[626EA2F4-ED14-3987-AEEE-C183C95B4731]@0xffffff7faa8a6000->0xffffff7faa8c3fff
            dependency: com.apple.kext.OSvKernDSPLib(530)[35810D8D-EDB2-331A-8E17-59879627A177]@0xffffff7faab74000->0xffffff7faab82fff
            dependency: com.apple.vecLib.kext(1.2.0)[AE5EFF10-F32C-3F4D-90D2-5C762C4E0519]@0xffffff7faaf3b000->0xffffff7faaffcfff
         com.apple.driver.AppleHDA(440.2)[D8129302-91D6-382A-9EEA-21DAE11270F1]@0xffffff7fa998a000->0xffffff7fa9a19fff
            dependency: com.apple.driver.AppleHDAController(440.2)[E92DDE1B-681C-33D3-9FA7-610AE5EB249B]@0xffffff7fa9a41000->0xffffff7fa9a53fff
            dependency: com.apple.driver.DspFuncLib(440.2)[A199D19B-2689-3DFF-B461-A5956BC976ED]@0xffffff7fa9a71000->0xffffff7fa9b53fff
            dependency: com.apple.iokit.IOAudioFamily(440.2)[626EA2F4-ED14-3987-AEEE-C183C95B4731]@0xffffff7faa8a6000->0xffffff7faa8c3fff
            dependency: com.apple.iokit.IOGraphicsFamily(597)[718E01CF-8B05-3042-88F4-DE3441395D00]@0xffffff7faa9c1000->0xffffff7faa9effff
            dependency: com.apple.iokit.IOHDAFamily(440.2)[900235B5-1D57-31BE-B43A-B2562B64C9FB]@0xffffff7fa9b65000->0xffffff7fa9b68fff
            dependency: com.apple.iokit.IONDRVSupport(597)[822CC0A2-790D-3CCE-B679-9B920226F533]@0xffffff7faaa15000->0xffffff7faaa1dfff

Process name corresponding to current thread (0xffffff99d4cf9598): kernel_task
Boot args: keepsyms=1 agdpmod=pikera -wegnoigpu 

Mac OS version:
22G90

Kernel version:
Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
Kernel UUID: 8295C77B-2AAB-3471-81B5-438F59B1A36D
roots installed: 0
KernelCache slide: 0x0000000014800000
KernelCache base:  0xffffff8014a00000
Kernel slide:      0x00000000148dc000
Kernel text base:  0xffffff8014adc000
__HIB  text base: 0xffffff8014900000
System model name: iMacPro1,1 (Mac-7BA5B2D9E42DDD94)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 4769732238
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000000011c4c5923
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000d8419501f 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff803b73a000 - 0xffffffa03b73a000
  . PGZ   : 0xffffff803b73a000 - 0xffffff803f73b000
  . VM    : 0xffffff803f73b000 - 0xffffff850ba6e000
  . RO    : 0xffffff850ba6e000 - 0xffffff86a50d4000
  . GEN0  : 0xffffff86a50d4000 - 0xffffff8b71407000
  . GEN1  : 0xffffff8b71407000 - 0xffffff903d73a000
  . GEN2  : 0xffffff903d73a000 - 0xffffff9509a6d000
  . GEN3  : 0xffffff9509a6d000 - 0xffffff99d5da0000
  . DATA  : 0xffffff99d5da0000 - 0xffffffa03b73a000
  Metadata: 0xffffffe42dc81000 - 0xffffffe44dc81000
  Bitmaps : 0xffffffe44dc81000 - 0xffffffe453c81000
  Extra   : 0 - 0

**Comment by liangyi9812** [comment]
I disabled NVMeFix.kext, and now everything is going fine.

**Comment by vandroiy2013** [comment]
Added manually

**Comment by liangyi9812** [comment]
> Added manually

Hi @vandroiy2013
I hope you're doing well. I recently submitted a Pull Request (#873) to the [AppleALC](https://github.com/acidanthera/AppleALC)] project, but it was closed. I'm eager to contribute to the project and would appreciate some guidance on how to improve my PR.

Could you please provide more specific feedback or suggestions on what needs to be addressed? I want to make sure that my contribution aligns with the project's requirements and standards. 

I'd like to mention that I've been using this LayoutID which i made for nearly a month now, and during this time, the audio functionality has been working smoothly. 

If you could point out the areas that need attention or share any insights on how I can modify the PR to meet the project's expectations, that would be immensely helpful.

I'm open to learning and making necessary adjustments to my code. Please feel free to share any technical details or concerns you might have, and I'll do my best to address them.

Thank you for your time and consideration. I appreciate the effort you put into maintaining this project and look forward to your feedback.

Best regards,
liangyi

**Comment by vandroiy2013** [comment]
It was added by me manually from your repository because you broke xml structure of PinConfig's info.plist and there was a conflicts.

**Comment by liangyi9812** [comment]
> It was added by me manually from your repository because you broke xml structure of PinConfig's info.plist and there was a conflicts.

I get what you meant, and I really appreciate your assistance and quick response!

**Pull request closed without merging**
