### PR TITLE
Add ALC236 Layout-ID 23 for Lenovo Air 13 IML(S530-13IML) by JudySL

### PR DESCRIPTION
**Pull request by JudySL**

### CODE REVIEW

**Comment by Andrey1970AppleLife** [comment]
You broke structures keys data in plists. Build kext in Xcode for fix.

**Comment by Andrey1970AppleLife** [comment]
You broke structures keys data in PinConfig. Build kext in Xcode

**Comment by Andrey1970AppleLife** [comment]
Delete PinConfigs.kext from Resources/ALC236 folder.

**Comment by vandroiy2013** [comment]
Merged manually

**Pull request closed without merging**
