### PR TITLE
Add ALC299 layout-id 23 for Dell XPS 13 9380

### PR DESCRIPTION
**Pull request by cowpod**
Fixes linein, subsequently fixes kernel_task going crazy on XPS 13 9380. No clue if this works on the 9360/9370.

### CODE REVIEW

**Comment by ZOUHIRZED** [comment]
where or how i can get compiled version of this  ? ( i have  xps 9380)

**Comment by cowpod** [comment]
You can clone the main source, and duplicate ALC299/platforms22.xml to platforms23.xml, and that's pretty much all I've done so far. The nodes are the same (25,18 and 23,33), with slight difference to pin paths. 
But that's irrelevant as I can't seem to get the mic and the headphone mic, nor the headphones and the speakers, to work at the same time.
If you want, you can remove the entire 33 and 25 node group in platforms22.xml to get only speakers and mic working, without the high CPU usage.

**Comment by cowpod** [comment]
oops. closing again!

**Comment by ZOUHIRZED** [comment]
to be honest i dont have that issue you mentioned (high cpu usage for kernel process ) .well i had it before  back then  i change cfg lock setting with extracted bios and that solved my problem. i thought you solved the issue with the mic from combo jack which often has distortion  alc plug fix from wdubaiyu repo fixed it but its not very optimal  , and then there is the issue with headphone become distorted  when increasing  the sound beyond a certain lvl (while sound is on)

**Comment by cowpod** [comment]
theres no sound out of headphones for me with or without alcplugfix (is also static). 
i already have cfg unlocked, still high kernel_task (~50%+)
the layout id doesn't work. any combination i do has either static, or no sound at all.

**Comment by ZOUHIRZED** [comment]
what bios you are using ? macos version ?  have you checked my issue opened here [https://github.com/wdubaiyu/Hackintosh-Dell-XPS-9380/issues/4](url)

**Comment by cowpod** [comment]
Thanks, checking it now.

**Comment by cowpod** [comment]
hey, my pin 18 (0x12) doesn't have an associated pin-ctl. what does yours have?

**Comment by ZOUHIRZED** [comment]
omg you were right about cpu usage if didnt mentioned it i wouldnt notice

**Comment by ZOUHIRZED** [comment]
Node 0x19 [Pin Complex] wcaps 0x40048b: Stereo Amp-In
  Control: name="Headset Mic Boost Volume", index=0, device=0
    ControlAmp: chs=3, dir=In, idx=0, ofs=0
  Amp-In caps: ofs=0x00, nsteps=0x03, stepsize=0x27, mute=0
  Amp-In vals:  [0x00 0x00]
  Pincap 0x00003724: IN Detect
    Vref caps: HIZ 50 GRD 80 100
  Pin Default 0x411111f0: [N/A] Speaker at Ext Rear
    Conn = 1/8, Color = Black
    DefAssociation = 0xf, Sequence = 0x0
    Misc = NO_PRESENCE
  Pin-ctls: 0x24: IN VREF_80

**Comment by ZOUHIRZED** [comment]
check my dump (its name is codec#0.txt)

**Comment by ZOUHIRZED** [comment]
i found that xps 9370 use the same codec  ( check this [https://osxlatitude.com/forums/topic/11167-applehda-patch-request/?do=findComment&comment=90791](url).  he built a applealc.kext for his codec using id 2 ,i dont how to get this working for us

**Comment by cowpod** [comment]
thank you. I think opencore doesn't properly dump the audio codec, fetching my codec from debian now.
I'm not sure if we have the exact same models, but hopefully we do. I'll try adding the pin-ctls verb to AppleALC, and see if that does anything...

**Comment by cowpod** [comment]
The high CPU usage by kernel_task appears to be caused by pin 0x19/25/linein, and I have no clue why. For now, I've disabled it. Attaching patched AppleALC and ALCPlugFix below, with layout-id 23.

What works: Speaker, Mic, Headphones.
What doesn't work: LineIn

**Comment by cowpod** [comment]
I looked at the archive you linked to; basically, it's identical with exception to the input pathmaps. I've tried them, but still the same as before.

8->35->25 (linein)
8->35->18 (mic)

If we remove linein, the mic works as well (mic works with any (reasonable) pathmap; 8->35->18 is one of them)

**Comment by ZOUHIRZED** [comment]
can you update the xcode for the appleacl/Alcplugfix (that you just updated)in your git for future reference thanks

**Comment by ZOUHIRZED** [comment]
why dont we use 0x1b for mic say 8 -> 35 -> 27 ? since that pin (for mic headphone)is present in Audio Mixer 0x23?

**Comment by cowpod** [comment]
yes, i've already set the linein mic to 8->35->27 for the applealc kext. i've also tried set_pin_widget_control on it, but still no input.

**Comment by ZOUHIRZED** [comment]
yeah and if you dont lower the mic volume you can hear static from the mic in your ear...the official release alc id 22

**Comment by ZOUHIRZED** [comment]
i found the source you were looking for in forum with id 58 calabash layout/platform #https://github.com/acidanthera/AppleALC/pull/405

**Comment by cowpod** [comment]
i cant seem to find the alc299 xml files. i think he only attached the compiled kext

**Comment by ZOUHIRZED** [comment]
image
he did indeed remove linein

**Comment by cowpod** [comment]
Attached source for AppleALC 1.5.5 and ALCPlugFix. Still can't get the LineIn to work.
[AppleALC-1.5.5.zip](https://github.com/acidanthera/AppleALC/files/5533809/AppleALC-1.5.5.zip)
[ALCPlugFix.zip](https://github.com/acidanthera/AppleALC/files/5533810/ALCPlugFix.zip)

**Pull request closed without merging**
