### PR TITLE
MSI Modern 15 A10M layout 29

### PR DESCRIPTION
**Pull request by hla63**
Hello, this is my PR for msi modern 15 A10M laptop 

Autoswitch headphone/speakers works

Audio works after sleep & windows reboot 

Thx narcyzzo & mikebeaton

### CODE REVIEW

**Comment by Andrey1970AppleLife** [comment]
You shall add pinconfig.

**Comment by hla63** [comment]
oup
[PinConfigs.kext.zip](https://github.com/acidanthera/AppleALC/files/8147155/PinConfigs.kext.zip)
s

**Comment by Andrey1970AppleLife** [comment]
To PR, not to post.

**Comment by hla63** [comment]
Should be Ok now :)

**Pull request merged**
