### PR TITLE
ALC255 Layout ID 22 fix sleep wake issues with headphone socket

### PR DESCRIPTION
**Pull request by feartech**

### CODE REVIEW

**Comment by feartech** [comment]
Forgive my ignorance, but will these changes be added in the next version of AppleALC.kext ?

Many thanks

**Comment by Core-i99** [comment]
> Forgive my ignorance, but will these changes be added in the next version of AppleALC.kext ?
> 
> Many thanks

Your pr is closed, so no they will not be implemented.

**Comment by feartech** [comment]
> > Forgive my ignorance, but will these changes be added in the next version of AppleALC.kext ?
> > Many thanks
> 
> Your pr is closed, so no they will not be implemented.

Any reason why and what I should do if there is an issue with my request?

**Comment by Core-i99** [comment]
Infi.plist - root of repostory, shouldn't be there
Pinconfigs.kext.zip - shouldn't be there
.md5 and .zlib files shouldn't be there


The only things which you should do: 
- add layout to pinconfigs.kext
- add layout and platforms to the info plist of alc255
- add layout and platforms xml file for your codec

**Comment by feartech** [comment]
ahh brilliant! thanks for that, will get on that :)

**Pull request closed without merging**
