### PR TITLE
Add LayoutID 69 For ALC282

### PR DESCRIPTION
**Pull request by hoseinrez**
Hey guys, I have added Layout 69 for ALC282 (Lenovo IdeaPad Z510).
This layout id is tested and following things are working :

- Internal Speakers Working + Good SignalProcessing
- Internal Microphone Working + AmbientNoiseReduction
- HeadPhone Jack Working + Auto Switch Output When Connected
- HeadPhone Microphone Working + Auto Switch Input When Connected

Let me know if there is a Problem ...

Thank You All AppleALC Devs 🤍

### CODE REVIEW

**Comment by SomeName6** [comment]
May I ask why you use those "No Connection" things? 
Schermafbeelding 2021-11-02 om 11 16 11

I am learning it a bit...but can't seem to understand that.

**Comment by SomeName6** [comment]
@hoseinrez

**Comment by hoseinrez** [comment]
hi, @SomeName6 ...
Sorry for my late, I really recommend reading [Guide1](https://github.com/F0x1c/AppleALC_Instructions) (By @F0x1c) and [Guide2](https://www.root86.com/blog/40/entry-51-guide-anleitung-patch-applehda/) (By @MacPeet)
Also checking structure of "LayoutID.xml" and "PlatformsID.xml" files in Original AppleHDA.kext (/System/Library/Extensions/AppleHDA.kext/Contents/Resources) and Acidanthera AppleALC.kext for better understanding of codec Layout injection.

About Your Question ...
After dumping your audio codec, you need all "pinComplex" nodes with "ControlNames" to follow their connection to other nodes, Because these nodes with their connections will give you inputs & outputs.

so other pinComplex nodes without ControlNames have no connection with other nodes and their ports should be set "No Connection" in PinConfigs.

I hope my brief explanation help you 😉

**Comment by SomeName6** [comment]
All my outputs and inputs are already working with my own applealc resources. Which I learned from the first guide. It seems like I must have missed that part.

I just kept seeing these no connection things in pinconfigs and now I finally learned when to use them. Really thank you for the explanation!

**Comment by antoniomcr96** [comment]
> * HeadPhone Microphone Working + Auto Switch Input When Connected

How did you enable autoswitching microphone?

**Comment by TheHackGuy** [comment]
> > * HeadPhone Microphone Working + Auto Switch Input When Connected
> 
> How did you enable autoswitching microphone?

If you open up his pinconfigs with the pinconfigurator app then you will see the "Jack Detect Override" setting being on under Misc
Schermafbeelding 2021-11-15 om 20 48 59

**Pull request merged**
