### PR TITLE
Updated Pin Config for layout 16 ALC1220

### PR DESCRIPTION
**Pull request by narcyzzo**
-Fixed sound not working after reboot from Windows with Realtek Driver installed
- Huge Thanks to @mikebeaton

### CODE REVIEW

**Comment by hla63** [comment]
Hello i see you use verbs 
020**500**07				
020**500**1a
020**401**c1

what 500 & 401 are supposed to do ?

**Comment by narcyzzo** [comment]
Those are per-machine specific, actaully i send `SET_COEF_INDEX` and 
`SET_PROC_COEF` to coeffs from sound-working-state to node `0x20`. Commands are modded since alc-verb not working correctly- fix soon(https://github.com/acidanthera/bugtracker/issues/1644). U need dump coeffs from not working state, compare them to working state and send them to work.

**Comment by hla63** [comment]
thanx for explanation !

**Comment by mikebeaton** [comment]
> Hi Those are per-machine specific, actaully i send `SET_COEF_INDEX` and `SET_PROC_COEF` to coeffs from sound-working-state to node `0x20`. See this why commands looks like this ([acidanthera/bugtracker#1644](https://github.com/acidanthera/bugtracker/issues/1644)). U need dump coeffs from not working state, compare them to working state and set correct ones. Write up will come soon.

Actually the normal verb/argument packing is not _because_ alc-verb has that bug (or quirk, compared to hda-verb), it's just how you pack the argument for 4 bit verbs (which iirc is all verbs that don't start with 7 or F).

**Comment by TheHackGuy** [comment]
> > Hi Those are per-machine specific, actaully i send `SET_COEF_INDEX` and `SET_PROC_COEF` to coeffs from sound-working-state to node `0x20`. See this why commands looks like this ([acidanthera/bugtracker#1644](https://github.com/acidanthera/bugtracker/issues/1644)). U need dump coeffs from not working state, compare them to working state and set correct ones. Write up will come soon.
> 
> Actually the normal verb/argument packing is not _because_ alc-verb has that bug (or quirk, compared to hda-verb), it's just how you pack the argument for 4 bit verbs (which iirc is all verbs that don't start with 7 or F).

Can you show an example of that? I never actually experimented with those verbs. But I don't understand what the issue is exactly when sending those verbs, why they shouldn't work in alc-verb tool but as well in the pinconfigs.

**Comment by mikebeaton** [comment]
There isn't a problem, the verbs are laid out fine.

I was just pointing out that the compressed verbs in the pinconfigs don't need to be in that format because anything about alc-verb.

Just as an example `020401c1` is pin 0x20 verb 0x400 value 0x01c1. Or if it was `02071534` it would be pin 0x20, verb 0x715, value 0x34. That's just the compressed format used by Intel HDA compliant chips.

**Comment by mikebeaton** [comment]
@vandroiy2013 @MacPeet Are you able to review this? The changes make sense to me, I worked with @narcyzzo to discover them.

The added verbs are:

02050007
020403c0
0205001a
020401c1

= set processing coefficient 0x07 on node 0x20 to 0x03c0 and set processing coefficient 0x1a on node 0x20 to 0x01c1.

They fix sound not working after Realtek driver for this card in Windows. They were derived by reading the working values of all the processing coefficients when booting direct, and comparing them to the non-working values when warm booting from Windows with Realtek. If you manually apply them in Linux with `hda-verb`, they also fix the sound in the same situation in Linux. We believe they are the minimal set of changes (only the 0x1a coeff change is needed on Linux, but both are needed in macOS; i.e. Linux half fixes the problem already).

**Comment by hla63** [comment]
Excuse me, how are you doing to dump coeffs ?

**Comment by mikebeaton** [comment]
In Linux you can dump them https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1850439/comments/153. For macOS I wrote a script to dump using `alc-verb`. Planning to do a write-up.

**Comment by hla63** [comment]
Thanks you very much !!!!!

I use another method to find these values.
I found RtHDDump on [Asus blog](https://asus-linux.org/blog/sound-2021-01-11/)
with these tool I can compare values on Node x20
**Microsoft audio Driver** versus **Realtek audio driver**.

& I found 
alc-verb 0x20 0x500 0x10
alc-verb 0x20 0x400 0x20
alc-verb 0x20 0x500 0x1a
alc-verb 0x20 0x480 0x0b

**sound works like a charm** with these commands on my msi laptop.

**Comment by MacPeet** [comment]
I hope the changes don't break the audio for users with the current layoutID16. Otherwise develop your own new ID!

**Comment by mikebeaton** [comment]
We believe it would actually fix for others, e.g. if you have Win with Realtek driver on your machine, this would probably fix the same issue of no sound after warm reboot into macOS from that.

If you're interested and able to test that'd be really great. If not, it is your layout, so if you prefer could definitely be a different very similar layout on an alternative number.

**Comment by MacPeet** [comment]
I don't have a Z390 myself.
I developed the codec for other users, so I can't try it myself.
I don't mind if the codec is changed if it's a win for all users.

**Comment by mikebeaton** [comment]
We used the same approach to generate final fixes for https://github.com/acidanthera/AppleALC/pull/759, and that is giving sound to other users who did not have it before. (On that card it was a case of no sound ever, except using Realtek driver in Windows.) So we think this approach is good. Very happy to rethink and separate the ids if any reports of any problems.

**Comment by mikebeaton** [comment]
Sorry for duplication, script and write-up here: https://github.com/mikebeaton/dump-coeff - feedback welcome.

**Pull request merged**
