### PR TITLE
ALC295 - Layout 33 for Dell Latitude 7210 2-in-1

### PR DESCRIPTION
**Pull request by Lorys89**
For fix combojack (mic ext+headphone) i use this 
[ALC295PlugFix-DELL.zip](https://github.com/acidanthera/AppleALC/files/14969997/ALC295PlugFix-DELL.zip)

### CODE REVIEW

**Comment by iwissemben** [comment]
Your layout and alcplug fix works also for Acer Nitro 5 AN515-55-51QY but on fresh boot the headsets output has a continuous hissing noise. That hissing noise totally disappears after a sleep-wake cycle. It would be great if we could find a fix. 

My tests regarding processing coeffs (linux vs macOS) hasn't lead anywhere except that node 0x20's processing cap 0x45 is directly involved in the modulation of that noise. I can't find a value that fixes it completely while keeping sound quality though.

**Comment by Lorys89** [comment]
> Your layout and alcplugfix works also for Acer Nitro 5 AN515-55-51QY but on fresh boot the headset's output has a continuous hissing noise present with and without audio playing. That hissing noise totally disappears after a sleep-wake cycle. It would be great if we could find a fix though.
> 
> My tests regarding processing coeffs (linux vs macOS) haven't led anywhere except that node 0x20's processing cap 0x45 is directly involved in the modulation of that noise. I can't find a value that fixes it completely while keeping sound quality though.
> 
> Also what's funny is that I encountered the same issue on linux, I fixed it by adding the line "options snd-hda-intel model=dell-headset-multi" to the also-base.conf file

Use alcplugfix with layout 21 which is for acer, the 33 is done on dump for dell pc, or create a new layout for your acer.

**Comment by Lorys89** [comment]
> Your layout and alcplugfix works also for Acer Nitro 5 AN515-55-51QY but on fresh boot the headset's output has a continuous hissing noise present with and without audio playing. That hissing noise totally disappears after a sleep-wake cycle. It would be great if we could find a fix though.
> 
> My tests regarding processing coeffs (linux vs macOS) haven't led anywhere except that node 0x20's processing cap 0x45 is directly involved in the modulation of that noise. I can't find a value that fixes it completely while keeping sound quality though.
> 
> Also what's funny is that I encountered the same issue on linux, I fixed it by adding the line "options snd-hda-intel model=dell-headset-multi" to the also-base.conf file

test this and use layout 34
[AppleALC-1.9.0-RELEASE.zip](https://github.com/acidanthera/AppleALC/files/15266223/AppleALC-1.9.0-RELEASE.zip)

**Comment by iwissemben** [comment]
> > Your layout and alcplugfix works also for Acer Nitro 5 AN515-55-51QY but on fresh boot the headset's output has a continuous hissing noise present with and without audio playing. That hissing noise totally disappears after a sleep-wake cycle. It would be great if we could find a fix though.
> > My tests regarding processing coeffs (linux vs macOS) haven't led anywhere except that node 0x20's processing cap 0x45 is directly involved in the modulation of that noise. I can't find a value that fixes it completely while keeping sound quality though.
> > Also what's funny is that I encountered the same issue on linux, I fixed it by adding the line "options snd-hda-intel model=dell-headset-multi" to the also-base.conf file
> 
> test this and use layout 34 [AppleALC-1.9.0-RELEASE.zip](https://github.com/acidanthera/AppleALC/files/15266223/AppleALC-1.9.0-RELEASE.zip) and if it doesn't work and you need it you can write on the macos86.it forum and we'll talk there

I tried the layour 34 with your kext but it didn't worked.

**Comment by kiki59665** [comment]
Hi Lorys89,


It's a pleasure to meet you. I have a Dell Latitude 7210 2-in-1, and I upgraded the network card to BCM94360Z4. The internet speed is normal. Recently, I installed MacOS 15.0. I've also tried installing Sonoma and Ventura before, but they ran very slowly. Every time I click on an application, it takes a long time to open, and it also takes a long time for the desktop to appear when I enter the system each time. I've tried many solutions I found online, but none of them worked.


I saw your article on the macos86.it forum, but I couldn't register and always failed to pass the registration process, so I couldn't download your EFI and BIOStoTXT. Therefore, if possible, could you send me the latest EFI and BIOS for the Dell Latitude 7210 2-in-1? I would like to try them out. My email is kiki59665@163.com. I'm looking forward to your reply and wish you all the best in your work!

**Pull request merged**
