### PR TITLE
Add ALC295 layout 23 for HP OMEN 15-AX000

### PR DESCRIPTION
**Pull request by Lancet-z**
Add ALC295 layout 23 for HP OMEN 15-AX000

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Hi
Where is ALC295/info.plist changes?

**Comment by Lancet-z** [comment]
> Hi
> Where is ALC295/info.plist changes?

**Comment by Lancet-z** [comment]
> Hi
> Where is ALC295/info.plist changes?

**Comment by Lancet-z** [comment]
I forgot. Now I've uploaded it

**Pull request merged**
