### PR TITLE
layout 14 CX8050 reduced internal mic gain

### PR DESCRIPTION
**Pull request by brunogermain**
Added layout14 to CX8050 codec to reduce the internal mic gain, which is otherwise always distorted

### CODE REVIEW

**Comment by vandroiy2013** [comment]
There is no pinconfig.

**Comment by brunogermain** [comment]
corrected

**Comment by vandroiy2013** [comment]
Now you broke info.plist XML structure. Build project in Xcode before PR.

**Comment by brunogermain** [comment]
Sorry, fixed it

**Pull request closed without merging**
