### PR TITLE
Add support for (Alldo)Cube Mix Plus (ALC283) id:13

### PR DESCRIPTION
**Pull request by Aldo97**
Please add this layout

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Where is pin configuration for this layout?

**Comment by Aldo97** [comment]
> Where is pin configuration for this layout?

Added. I forgot to add PinConfigs to the commit.

**Comment by vandroiy2013** [comment]
Fix XML structure in info.plist

**Comment by Aldo97** [comment]
> Fix XML structure in info.plist

Don't know what happened, I've only added the new dictionary with the plist editor.
Locally, reading the info.plist file with the text editor, it seems all ok. Don't know how to fix it...

**Comment by vandroiy2013** [comment]
Build project before making PR.

**Comment by Aldo97** [comment]
Don't merge this commit for now.
It seems that this works on Catalina but not in Big Sur.
In Big Sur the internal speaker is not working...
This is strange because it is detected and the internal mic and the headphones work without any problem.
I'll investigate and fix the issue.

**Comment by Aldo97** [comment]
Now it works on Big Sur.

**Pull request merged**
