### PR TITLE
Added layout 69 for ASRock Z490M ITX/AC ALC1200(display as ALCS1200A)

### PR DESCRIPTION
**Pull request by Lorys89**
Added layout 69 for ASRock Z490M ITX/AC ALC1200(display as ALCS1200A)
By Lorys89 and Vorshim92

(also work on Asrock : Z490 Phantom Gaming 4 - Z490M PRO4)

### CODE REVIEW

**Comment by zampemo** [comment]
This might actually work with my ROG H470-I motherboard as I have the same chipset and I can't find a better layout-id to get it to fully work (I have unrecognized audio on both the front header jacks (headphones and mic, on the case) and the audio from the HDMI monitor. I can only have audio when I connect my headphones on the green "Line-out" hole, though without mic capabilities for eg. using standard Apple EarPods.

**Comment by atomizasser** [comment]
Which is the difference with layout 49 added [perviously](https://github.com/acidanthera/AppleALC/commit/8f9406ae6a93bc96400cda0096b78b7c1696dc9d#diff-fe21d04b531a708e1827621476af47ea36f40e455b4257459a38eda8fe2465d6) by VanXNF?

**Comment by Lorys89** [comment]
> Qual è la differenza con il layout 49 aggiunta [perviously](https://github.com/acidanthera/AppleALC/commit/8f9406ae6a93bc96400cda0096b78b7c1696dc9d#diff-fe21d04b531a708e1827621476af47ea36f40e455b4257459a38eda8fe2465d6) da VanXNF?

Work line in and microphone front and rear work good

**Comment by atomizasser** [comment]
Tested! Microphone works better than before! and also "Ambient noise reduction" can be selected! Good work!

**Comment by zampemo** [comment]
> > Qual è la differenza con il layout 49 aggiunta [perviously](https://github.com/acidanthera/AppleALC/commit/8f9406ae6a93bc96400cda0096b78b7c1696dc9d#diff-fe21d04b531a708e1827621476af47ea36f40e455b4257459a38eda8fe2465d6) da VanXNF?
> 
> fixed line in (now work) and fixed microphone front and rear (now work good)
> test layout 69
> [AppleALC-1.6.1-RELEASE.zip](https://github.com/acidanthera/AppleALC/files/6447138/AppleALC-1.6.1-RELEASE.zip)

Ciao Loris, I've tested 1.6.1 with alcid=69 on my Rog H470-I, but I have zero interfaces found (I know it's a different mobo) as opposed to alcid=7 which seems the best alternative for me. How can I really find the right one, apart from changing that number with the ones indicated on the Wiki? Could it be that I (still) have an unsupported revision? Can I find the exact HW ID on Windows? I've looked everywhere and did multiple tests, but I may have missed something. Thanks.

**Comment by Lorys89** [comment]
> > > Qual è la differenza con il layout 49 aggiunta [perviously](https://github.com/acidanthera/AppleALC/commit/8f9406ae6a93bc96400cda0096b78b7c1696dc9d#diff-fe21d04b531a708e1827621476af47ea36f40e455b4257459a38eda8fe2465d6) da VanXNF?
> > 
> > 
> > fixed line in (now work) and fixed microphone front and rear (now work good)
> > test layout 69
> > [AppleALC-1.6.1-RELEASE.zip](https://github.com/acidanthera/AppleALC/files/6447138/AppleALC-1.6.1-RELEASE.zip)
> 
> Ciao Loris, I've tested 1.6.1 with alcid=69 on my Rog H470-I, but I have zero interfaces found (I know it's a different mobo) as opposed to alcid=7 which seems the best alternative for me. How can I really find the right one, apart from changing that number with the ones indicated on the Wiki? Could it be that I (still) have an unsupported revision? Can I find the exact HW ID on Windows? I've looked everywhere and did multiple tests, but I may have missed something. Thanks.

your codec (https://github.com/acidanthera/AppleALC/tree/master/Resources/ALCS1220A)is different to my codec (https://github.com/acidanthera/AppleALC/tree/master/Resources/ALCS1200A)

**Comment by Andrey1970AppleLife** [comment]
Synchronize repository and build kext for fix ConfigData in one line.

**Comment by Lorys89** [comment]
close this pr and re open new in one line

**Pull request closed without merging**
