### PR TITLE
Replace 200 Series (0xA2F0) PCH HD Audio patch.

### PR DESCRIPTION
**Pull request by TheHackGuy**
Stop using the ugly way of patching pci id checks. 

Tested and confirmed working on macOS 12.1

Lilu debug log attached:
[Lilu_1.5.8_21.2.txt](https://github.com/acidanthera/AppleALC/files/7773736/Lilu_1.5.8_21.2.txt)

Screenshot from ioreg which shows 0xA2F0 device id:
Screen Shot 2021-12-24 at 10 38 45

@vandroiy2013 Do you think it's needed to test this patch on older version then 12.1?

### CODE REVIEW

**Comment by TheHackGuy** [comment]
@Andrey1970AppleLife 
What's wrong?

**Comment by vandroiy2013** [comment]
@TheHackGuy Please test it in older OS versions.

**Comment by Andrey1970AppleLife** [comment]
1. It not tested on old OS.
2. You set min kernel Catalina.

**Comment by Andrey1970AppleLife** [comment]
Need min kernel 16 and test on 10.12+

**Comment by TheHackGuy** [comment]
> Need min kernel 16 and test on 10.12+

 I will test on all versions from 10.12 to 12.1 and then upload screenshots. 

Will probably take a bit time, I think I can do this before January release.

**Comment by TheHackGuy** [comment]
I'm just going to comment every time I test an macOS version. 

This is Big Sur 11.6.2
Screenshot 2021-12-24 at 07 43 41

**Comment by TheHackGuy** [comment]
I'm just going to comment every time I test a macOS version. 

This is Big Sur 11.6.2

Screenshot:
Screenshot 2021-12-24 at 07 43 41

Lilu log:
[Lilu_1.5.8_20.6.txt](https://github.com/acidanthera/AppleALC/files/7774751/Lilu_1.5.8_20.6.txt)

**Comment by Andrey1970AppleLife** [comment]
You shall check also digital audio from IGPU.

**Comment by TheHackGuy** [comment]
> You shall check also digital audio from IGPU.

Ok.
Here is a screenshot from Big Sur 11.6.
Screenshot 2021-12-24 at 09 58 49
2

I'm probably going to continue testing on other macOS versions tomorrow.

**Comment by TheHackGuy** [comment]
I noticed that sometimes HDMI audio only worked 1 time with the new controller patches. 
Then I started investigating and tried to replace the patch with 0xA170 instead of 0x9D70, with that change HDMI audio works now every time when booting up on Catalina, Big Sur and Monterey. Commit will be created over a couple minutes. 


Catalina 10.15.7 (19H15):

Screenshot:
Screenshot 2021-12-25 at 08 23 33

Lilu log:
[Lilu_1.5.8_19.6.txt](https://github.com/acidanthera/AppleALC/files/7776029/Lilu_1.5.8_19.6.txt)

**Comment by TheHackGuy** [comment]
Mojave 10.14.4 (18E2034):

Screenshot:
Screenshot 2021-12-26 at 01 36 54

Lilu log:
[Lilu_1.5.8_18.5.txt](https://github.com/acidanthera/AppleALC/files/7776798/Lilu_1.5.8_18.5.txt)

**Comment by TheHackGuy** [comment]
High Sierra 10.13.6 (17G66): 

Problem: 
Can't test HDMI audio of the IGPU. My cpu is an i5 9400 and coffee lake igpu is supported since 10.14.
Solving:
- Take the risk that someone gets problems with their HDMI audio and keep the patch. This patch just also uses 0x9D70 like the previous patch did, it's supposed to work.
- Inject the High Sierra AppleHDA to Mojave?
- Keep the previous patch with min kernel Sierra and maxkernel High Sierra. Then use the new patch for Mojave to latest macOS. 

Hackintool shows HDMI audio device, so I guess it's fine.

Screenshot:

**Comment by TheHackGuy** [comment]
High Sierra 10.13.6 (17G66):

Screenshot:
Screen Shot 2021-12-26 at 03 33 15

Lilu log:
[Lilu_1.5.8_17.7.txt](https://github.com/acidanthera/AppleALC/files/7777151/Lilu_1.5.8_17.7.txt)

Problem: Can't test HDMI audio, my cpu is CFL and the iGPU is unsupported in 10.13. HDMI audio show in Hackintool and ioreg so I guess it's fine? 
@vandroiy2013 or @Andrey1970AppleLife

**Comment by Andrey1970AppleLife** [comment]
>  HDMI audio shows in Hackintool and ioreg so I guess it's fine?

No, it doesn't mean what to working.
We can't accept your changes without test on KBL.
We can't allow breakage KBL.
It isn't necessary to break that that works.

**Pull request closed without merging**
