### PR TITLE
add NEW ALC256 Layout-id 16 for Dell 7000 Series with 2.1Ch

### PR DESCRIPTION
**Pull request by vicjl**

### CODE REVIEW

**Comment by jbergonia** [comment]
Hi @vandroiy2013 @vicjl I encountered headphone jack issues for this layout id. 
I'm using Catalina running on Dell 7567 Gaming Laptop. 
Specs found here: https://laptopmedia.com/laptop-specs/dell-inspiron-15-7567-70/

Try replicating these 2 issues:
- 1st issue: On fresh start (no headphones plugged in on device), try plugging in any headphone. Headphone jack is shown / switched on `Sound` settings but it won't produce any sound.
- 2nd issue: Plug in any headphone / external speaker then try restarting the machine without unplugging it. It will produce noise after the restart.

I'm switching back to layout id `21` for now as I didn't have any problem on that layout id regarding plugging and unplugging headphones / external speakers and no noise produced (even left plugged in after restart). You may also check that one.

**Comment by vicjl** [comment]
> Hi @vandroiy2013 @vicjl I encountered headphone jack issues for this layout id.
> I'm using Catalina running on Dell 7567 Gaming Laptop.
> Specs found here: https://laptopmedia.com/laptop-specs/dell-inspiron-15-7567-70/
> 
> Try replicating these 2 issues:
> 
> * 1st issue: On fresh start (no headphones plugged in on device), try plugging in any headphone. Headphone jack is shown / switched on `Sound` settings but it won't produce any sound.
> * 2nd issue: Plug in any headphone / external speaker then try restarting the machine without unplugging it. It will produce noise after the restart.
> 
> I'm switching back to layout id `21` for now as I didn't have any problem on that layout id regarding plugging and unplugging headphones / external speakers and no noise produced (even left plugged in after restart). You may also check that one.



> Hi @vandroiy2013 @vicjl I encountered headphone jack issues for this layout id.
> I'm using Catalina running on Dell 7567 Gaming Laptop.
> Specs found here: https://laptopmedia.com/laptop-specs/dell-inspiron-15-7567-70/
> 
> Try replicating these 2 issues:
> 
> * 1st issue: On fresh start (no headphones plugged in on device), try plugging in any headphone. Headphone jack is shown / switched on `Sound` settings but it won't produce any sound.
> * 2nd issue: Plug in any headphone / external speaker then try restarting the machine without unplugging it. It will produce noise after the restart.
> 
> I'm switching back to layout id `21` for now as I didn't have any problem on that layout id regarding plugging and unplugging headphones / external speakers and no noise produced (even left plugged in after restart). You may also check that one.

Hello, @jbergonia   because of the particularity of alc256, we need extra kext to resolve the headphone issues. Such as "ComboJack" or "AlcPlugFix". Both can be found in GitHub. I recommend using ComboJack with this layout id. Please check whether the issues are resolved after using.

**Comment by vicjl** [comment]
> Hi @vandroiy2013 @vicjl I encountered headphone jack issues for this layout id.
> I'm using Catalina running on Dell 7567 Gaming Laptop.
> Specs found here: https://laptopmedia.com/laptop-specs/dell-inspiron-15-7567-70/
> 
> Try replicating these 2 issues:
> 
> * 1st issue: On fresh start (no headphones plugged in on device), try plugging in any headphone. Headphone jack is shown / switched on `Sound` settings but it won't produce any sound.
> * 2nd issue: Plug in any headphone / external speaker then try restarting the machine without unplugging it. It will produce noise after the restart.
> 
> I'm switching back to layout id `21` for now as I didn't have any problem on that layout id regarding plugging and unplugging headphones / external speakers and no noise produced (even left plugged in after restart). You may also check that one.

Hello, @jbergonia because of the particularity of alc256, we need extra kext to resolve the headphone issues. Such as "ComboJack" or "AlcPlugFix". Both can be found in GitHub. I recommend using ComboJack with this layout id. Please check whether the issues are resolved after using.

**Comment by jbergonia** [comment]
Hi @vicjl Already tried that. It's not working on my end (still hearing noise when headphone is plugged).

**Comment by vicjl** [comment]
> Hi @vicjl Already tried that. It's not working on my end (still hearing noise when headphone is plugged).

Hi @jbergonia This id(with ComboJack) works well on my laptop(Dell Ins 7567). Before I pulling this id, at least five people who have the same model (i5 and i7) tested it . After pulling, nobody replicating the similar issues (For the same model, we have a group). Sorry about that but if you have any similar issues(after using ComboJack)with this id, please try another.
Thanks for your comment.

**Comment by maxis7567** [comment]
any new about headphone jack?

**Pull request merged**
