### PR TITLE
Add new layout alc887 for motherboard ASUS PRIME B250-PLUS

### PR DESCRIPTION
**Pull request by 0th3r**

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Hi. Custom layout.xml and platforms.xml must use similar numbers. If you use layout50 then your platforms must be also platforms50.

**Comment by 0th3r** [comment]
Hi. Done.

**Comment by hieplpvip** [comment]
@0th3r I think you should combine all into 1 commit

**Comment by 0th3r** [comment]
Done, it wasn't easy.

**Comment by vandroiy2013** [comment]
Thanks

**Pull request merged**
