### PR TITLE
Layout 21 for ALC285, layout22 for ALC298, Layout21 for ALC299, layout21 for CX20753, Layout21 for ALC233, Layout21 for IDT 92HD73C1X5, Layout21 for ALC294, Layout21 for ALC256, Layout21 for CX8200, Layout21 for CX20751/2

### PR DESCRIPTION
**Pull request by andreszerocross**
Fix for ALC285
- Mute Disable Audio Icon (when Fn + Mute Audio Button Pressed)
- Delete Unused Node

Fix Audio Out and in for ALC298 for Razer Blade 14 2017

### CODE REVIEW

**Comment by andreszerocross** [comment]
Update : Layout21 for ALC299 Acer Helios 500

**Comment by andreszerocross** [comment]
Update :
Layout21 for CX20753 for LG gram 15ZD960-GX5BK

**Comment by andreszerocross** [comment]
Update : 
Add layout 21 ALC233 for Asus A451LB-WX076D

**Comment by andreszerocross** [comment]
Update PinConfig, layout and platform 21 for ALC299

**Comment by andreszerocross** [comment]
Update : 
Layout 21 for Alienware M17X R2

**Comment by andreszerocross** [comment]
Update : Add layout 21 for ALC294 ASUS ZenBook Flip 14 UX461UA

**Comment by andreszerocross** [comment]
Update :
Add layout21 for CX8200 of HP Spectre 13-V130NG

**Comment by vit9696** [comment]
Hi, are you sure that all these are absolutely necessary? We are fine to merge them, yet the amount of new files exceeds most adequate estimates. Do the codecs differ that much that unified resources are not suitable?

**Comment by andreszerocross** [comment]
Update :
Layout21 for CX20751
All Works
No Need Custom CodecCommander or CodecCommander + SSDT Profile

**Comment by andreszerocross** [comment]
> Hi, are you sure that all these are absolutely necessary? We are fine to merge them, yet the amount of new files exceeds most adequate estimates. Do the codecs differ that much that unified resources are not suitable?

Yes,, before make a source,,, i try all layout in AppleALC.kext official release.
I write detail of notebook series,, I never make new resource before try it first.

**Pull request merged**
