### PR TITLE
add NEW ALC215 layout-id 18 for HP 830 G6

### PR DESCRIPTION
**Pull request by 965987400abc**
Built-in microphone, speaker, headset normal. External microphone sleep wake does not work

### CODE REVIEW

**Comment by miki9987** [comment]
Stop working after reboot from Windows 10.. any solution for this or should I look in Codec Commander for that?
Thanks

**Comment by jepjepus** [comment]
Hello, "neighbours" ;)

External to your project.
I am a Debian user just trying to make ALC215 microphone inputs work in an HP 830 G6.

Any info about it for debugging and so?

Thanks

**Comment by vit9696** [comment]
Hi! Well, if Linux has node sequences or similar, you can try feeding Linux with the data from the layouts from AppleALC.

**Comment by jepjepus** [comment]
> Hi! Well, if Linux has node sequences or similar, you can try feeding Linux with the data from the layouts from AppleALC.

I don't know. I've digging around and feel your codifications in integers (32 bit) and text for... dsp code? are really rare. Coding in Linux kernel would be in snd_hda_intel driver and I am still looking there.
May be a translation from one to another but perhaps it would be a hard way...
Thanks

**Comment by jepjepus** [comment]
What are the long "data" fields in layout XML files, in the ParameterInfo of DspFunction?
Are they base64 uuencoded?

Under Linux, codec programming goes like this:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/sound/pci/hda/patch_realtek.c?h=v5.6.2

**Comment by roddy20** [comment]
> What are the long "data" fields in layout XML files, in the ParameterInfo of DspFunction?
> Are they base64 uuencoded?
no one knows for sure
You may copy it from original Mac and it works
but there is no way to control it, AFAIK

**Comment by Joaotcs** [comment]
Hello! I have an 830 G6. It doesn't work properly... Internal mic is recognized but doesn't work. External mic isn't recognized...
@965987400abc, any Idea how to fix it?

**Comment by everyb313** [comment]
Hi same for me (840G6)
Internal mic is detected but doesn't work
Any progress on this topic ?

**Comment by mahdose** [comment]
> What are the long "data" fields in layout XML files, in the ParameterInfo of DspFunction?
> Are they base64 uuencoded?
> 
> Under Linux, codec programming goes like this:
> 
> https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/sound/pci/hda/patch_realtek.c?h=v5.6.2

Here we go, almost I am trying to gather all parties in this for a real work! I should have mailed you if it's the right one though

**Comment by kingo132** [comment]
Alienware a51m r2 wich ALC215 inside, there are two problems, first default is reset to Headphone on every boot, second the headphone audio is buzzing and disturbed.

**Comment by Snakespeed** [comment]
> Alienware a51m r2 wich ALC215 inside, there are two problems, first default is reset to Headphone on every boot, second the headphone audio is buzzing and disturbed.

Double check that your microphone is enabled in BIOS, 4-pin headphones will buzz like crazy otherwise.

**Pull request merged**
