### PR TITLE
Add Z690 PCH cAVs Patch (pci8086,7ad0)

### PR DESCRIPTION
**Pull request by R-a-s-c-a-l**

### CODE REVIEW

**Comment by vit9696** [comment]
Hello, could you tell us more details about this patch? Have you tested it? The board we have at hand has USB audio, so we have not checked the analog HDEF yet.

**Comment by R-a-s-c-a-l** [comment]
I tested on ASUS Z690m PLUS😄
Before ：
image

After ：
image

**Comment by vit9696** [comment]
Hmmm, right. But the patch looks a bit strange, I have a feeling it can be cleaner. Could you the IOReg here?

**Comment by vit9696** [comment]
Also, could you tell us how did you come up with this patch?

**Comment by R-a-s-c-a-l** [comment]
At first I tried to use it
Find: 70a10000 | replace: 7ad00000
Find: 868070a1 | replace: 86807ad0
AppleHDAController & AppleHDA can be loaded, but analog audio still doesn't work
This is the log:
截屏2021-11-14 下午4 23 02

**Comment by vit9696** [comment]
This code of yours spoofs the codec id with 0xA348, just in an ugly way. Could you try:

```
Find: 48a30000 | replace: 7ad00000
Find: 868048a3 | replace: 86807ad0
```

If it does not work, I guess we can go this route, because likely there is some extra `cmp` making it difficult to approach like this.

**Comment by vit9696** [comment]
Please also change the comment to something like `600 Series(0x7AD0) PCH HD Audio` to follow the scheme.

**Comment by Andrey1970AppleLife** [comment]
And move a patch to the file end.

**Comment by R-a-s-c-a-l** [comment]
When I try to replace the find value with 709d or 48a3, the situation is the same as 70a1 😭

**Comment by vit9696** [comment]
Yeah, let's stick to your patch then. Please follow the requests in https://github.com/acidanthera/AppleALC/pull/726#issuecomment-968264263 and https://github.com/acidanthera/AppleALC/pull/726#issuecomment-968265780 though. Thanks!

**Comment by R-a-s-c-a-l** [comment]
Replaces device-id 48a3 with d07a analog audio doesn't work, but patches out AppleHDAController PCI ID check and replaces internal variable content with 48A3 It is effective, I'm so confused 🤔️

**Comment by R-a-s-c-a-l** [comment]
👌

**Pull request closed without merging**
