### PR TITLE
Complete 295 for Asus UX430UA

### PR DESCRIPTION
**Pull request by gulios**

### CODE REVIEW

**Comment by vandroiy2013** [comment]
Hi
In latest commit ALC295 for Asus UX430UA already present.

**Comment by gulios** [comment]
I know, but there is a bug with "mute" on 295 so that's why i pulled fixed code.

**Comment by vandroiy2013** [comment]
Well @insanelydeepak told me in private conversation that all two layouts works fine. You should contact him.

**Comment by gulios** [comment]
ok, thanks, i've contacted with him in
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/issues/51

12/14/15 for 295 on UX430AU don't work in 100%
@insanelydeepak will contact with you and i hope we chose one working id ;)

Thank you.

**Pull request closed without merging**
