### PR TITLE
Added layout-id 35 for the ALC274

### PR DESCRIPTION
**Pull request by jackjack1-su**
New layout-id 35 for Realtek ALC274-Surface Pro 7

### CODE REVIEW

**Comment by athulda** [comment]
@jackjack1-su I know this is off topic considering the scope of this code review, but I would like to add support for IDT92HD94 as well in AppleALC.
Do you mind helping me navigating through the right step?
I tried following [Documentation](https://github.com/acidanthera/AppleALC/wiki/Adding-codec-support) but that seems to be outdated. 

Thanks in advance!

**Comment by jackjack1-su** [comment]
My step is a little different by the document--I use the VoodooHDA to get the configdata and the platform 
You can load the VoodooHDA first and then run the Getdump tool to get the node dump, then form and fix the pinconfig and node route.
At last,put them into the AppleALC/Resources/[Your sound card]/Platform**.xml and AppleALC/Resources/Pinconfigs.kext/Content/Info.plist


Warn:use Xcode to edit the plist!!!Or you will BREAK the XML STRUCTURE!!!

**Comment by pedrohqb** [comment]
> My step is a little different by the document--I use the VoodooHDA to get the configdata and the platform
> You can load the VoodooHDA first and then run the Getdump tool to get the node dump, then form and fix the pinconfig and node route.
> At last,put them into the AppleALC/Resources/[Your sound card]/Platform**.xml and AppleALC/Resources/Pinconfigs.kext/Content/Info.plist
> 
> Warn:use Xcode to edit the plist!!!Or you will BREAK the XML STRUCTURE!!!

Could you help me on that? I am trying to add Lenovo m93p Tiny support. Alc=15 works almost perfectly; the only thing that is wrongly configured is the mic input jack (it is considered an internal mic); the mic from headset jack works perfectly.

**Comment by Andrey1970AppleLife** [comment]
Remove plist tags from xml.
As here: https://github.com/acidanthera/AppleALC/commit/a6a6a142a95487a31fe434eb8941fc589eace4f6

**Pull request merged**
